### ISSUE TITLE
[Minor][UI][Mobile] The UI doesn't "perfectly" fit the screen in some case

### ISSUE THREAD

**Issue by BreadlyUwU** [pixelfed/pixelfed#392] opened 2018-08-19 07:48 UTC
*(Disclaimer: Since english isn't my native language, I'll just do my best for being understandable, in advance sorry if finally my post is not)*

After testing Pixelfed (on pixelfed.social) via my smartphone (Huawei Honor 7) I've seen there's an issue with the UI. Even if Pixelfed seem to be "responsive", it's look like the "box" that display user's posts is too big compared to the header (and more important, the screen resolution).

**Entering the UI** : [screen 1](https://user-images.githubusercontent.com/28685939/44306525-d6d98d80-a390-11e8-8cc2-a2d8ca7c6e05.png)

**What I got if I slide to the right** : [screen 2](https://user-images.githubusercontent.com/28685939/44306527-e8229a00-a390-11e8-8ede-a7c8ff722c17.png)

In fact even if I don't really thing that's a big deal since the mobile UI is still very usable, that make me feel like the UI isn't really adapted for the mobiles.

But, I don't really get what are the condition for getting this "issue" with the UI. I've reproducted this on Firefox (PC) when resizing the screen to an "mobile-like" screen ratio, but with an another device (Nexus 7 2012 tablet) wich have a lower width resolution than the Honor 7 (only 800px here), the bug doesn't occur:

**Pixelfed on Nexus 7 (= Perfect)** : [screenshot_20180819-092352](https://user-images.githubusercontent.com/28685939/44306584-3b491c80-a392-11e8-83e9-a5a13481ecad.png)

I'm assuming that I'm not the first who encountered this (again) minor ui inconvenience, but after a little research on this Github repo I haven't seen an issue talking about this (or I haven't searched enough), so, voilà.

Meanwhile... _*/me sending love to the Pixelfed project*_ ❤️

**Comment by mkljczk** [comment] 2018-08-19 15:56
[screenshot_20180819-175508](https://user-images.githubusercontent.com/21127288/44310580-16c46300-a3d9-11e8-99e3-aed6e5d82195.png)
The same thing happens on my Pixel 2 XL
margin-right seems to be a reason

**Comment by trwnh** [comment] 2018-08-19 22:03
Duplicate of / related to #338

**Closed as completed** 2018-08-21 21:52 UTC
