### ISSUE TITLE
Add Invite Code Redemption To Registration

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1651] opened 2019-08-30 19:53 UTC
Suggesting an option to use invitation codes 

This will allow invites to groups, trial, testers, etc without having to disable/enable registration

Found this package:
https://packagist.org/packages/clarkeash/doorman

Requires
-php: >=7.1.3
-laravel/framework: ^5.6
-ramsey/uuid: ^3.6

**Comment by trwnh** [comment] 2019-08-31 05:02
Possible duplicate of #805

**Comment by dansup** [comment] 2019-09-06 01:15
Yes lets move this to #805, I'd like to add this before v0.11

**Closed as completed by dansup** 2019-09-06 01:15 UTC
