### ISSUE TITLE
[feature] CDN_host for static files

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#4446] opened 2023-06-03 07:11 UTC
Can we please get Pixelfed to consider a Mastdon CDN_HOST style?

Serving all of the css/js/local static stuff from a CDN results ins a massive decrease on my servers general load because it's only handling the dynamic traffic.

## Example of mastodon sharing static js/css/svg/etc from the CDN
![image](https://github.com/pixelfed/pixelfed/assets/17537000/2f3b8107-facb-4d35-9f26-b67da11ee311)

Image showing all of the static files on my bunny CDN... and the API calls being handled by the server.
![image](https://github.com/pixelfed/pixelfed/assets/17537000/88f21fd3-355c-48bd-a251-b94f674f7ace)

**Comment by shleeable** [comment] 2023-06-03 07:18
These files can be CDN cached for example.
![image](https://github.com/pixelfed/pixelfed/assets/17537000/58c40ae4-ebdd-44ee-bd1a-eb55de913ee7)

**Comment by trwnh** [comment] 2024-05-31 15:18
Duplicate of #3782

**Closed as not planned by trwnh** 2024-05-31 15:18 UTC
