### ISSUE TITLE
Possibility to jump form images to images

### ISSUE THREAD

**Issue by dadall** [pixelfed/pixelfed#448] opened 2018-09-06 08:32 UTC
Hey,

I've been told it could be great to be able to start viewing an image and being able to see the next or previous post by simply clicking on an arrow or whatever. It will help to simply see all the posts of a user.

As an example, it may looks like the "album's view", for all posts of a profil.

dada

**Comment by dansup** [comment] 2018-09-15 17:14
Duplicate of #304

**Closed as completed by dansup** 2018-09-15 17:14 UTC
