### ISSUE TITLE
Hashtags don't show up in search when boosted to Mastodon

### ISSUE THREAD

**Issue by kvibber** [pixelfed/pixelfed#474] opened 2018-09-18 00:50 UTC
Hello! Maybe you've already fixed this in code that hasn't made it to pixelfed.social yet, or maybe it's already on your list (I know federation isn't complete yet), but I thought I'd bring it up.

I was experimenting with boosting Pixelfed posts to Mastodon, and found that while I was able to boost a photo and get it to show up in the appropriate timelines, it would not show up in hashtag searches on Mastodon.

I haven't found any clear indication of what Mastodon uses for searching on hashtags, but I compared the JSON data for a PixelFed post and a Mastodon post that both have hashtags. The Mastodon post has a tag array containing a list of these: `{"type":"Hashtag","href":"url-of-hashtag-on-home-instance","name":"#name-of-hashtag"}`, but the Pixelfed post's tag array is empty. Somewhere to start, at least.

Thank you!

**Comment by orithena** [comment] 2018-09-18 17:21
@kvibber: Wait wait wait... how have you been able to boost pixelfed content to mastodon? Thats what I've been trying to achieve for the last two weeks, but I did never get to the point where I was able to see pixelfed posts from mastodon...

**Comment by kvibber** [comment] 2018-09-18 18:01
@orithena I'm pasting the full URL of the Pixelfed post in the Mastodon search box. It shows the content like a Mastodon post, with up to 4 photos as attachments, and I can reply or boost on the Mastodon instance, though of course the results don't make it back to Pixelfed yet.

**Comment by orithena** [comment] 2018-09-18 19:12
@kvibber: Ah, thank you. I was trying to follow myself from mastodon and see if my photo posts appear there...

**Comment by dansup** [comment] 2018-09-23 03:27
Federation support is not finished yet, this is a duplicate of #1

**Closed as completed by dansup** 2018-09-23 03:27 UTC
