### ISSUE TITLE
Leaving feed then Liking

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#178] opened 2018-06-03 14:40 UTC
When I am looking at my feed and I :heart: a picture, it automatically leaves the feed and goes to that pictures page. Forcing me to scroll all the way back through the timeline to get where I was. 

Not sure if this is a planned thing...but I should be able to :heart: in the feed without leaving it.

**Comment by dansup** [comment] 2018-06-03 19:59
Duplicate of #87

**Closed as completed by dansup** 2018-06-03 19:59 UTC
