### ISSUE TITLE
Email validate in register

### ISSUE THREAD

**Issue by EugeneVdovenko** [pixelfed/pixelfed#4337] opened 2023-05-01 20:42 UTC
The "continue" button is not active when registering by invite after entering an e-mail address as kind <just_digits>@domain.tld

If before "@" will be write alphabetical string - "continue" button to activate.
| Just digits | Start with letter |
|--------|--------|
| ![2023-05-01_23-38-13](https://user-images.githubusercontent.com/9274923/235527561-f3488724-7299-43f2-be23-ab4bfaca8915.png) | ![2023-05-01_23-39-13](https://user-images.githubusercontent.com/9274923/235527585-e2a10ff1-ddc7-4381-818a-90be4540d4c7.png) |

**Comment by mamarguerat** [comment] 2023-05-02 15:23
Same problem if the address contains a `+` sign, for example `example+label@domain.tld`

**Comment by trwnh** [comment] 2024-05-31 06:35
Duplicate of #4264

**Closed as not planned by trwnh** 2024-05-31 06:35 UTC
