### ISSUE TITLE
Next/Previous arrows aren't visible if the photo has white background

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#796] opened 2019-01-24 00:10 UTC
How to reproduce:
1. upload 2 pictures that are just a white rectangle to make a double-picture post
2. Look at the timeline
3. Try to find the Next/previous arrows

Current result: The arrows are pure white and are therefore not visible on white background.

Expected result: The arrows have a border or shadow to make them visible over white background.

Screenshot: https://imgur.com/a/om1HA9d

**Comment by trwnh** [comment] 2019-03-02 22:02
Duplicate of #267

**Closed as completed by trwnh** 2019-03-02 22:02 UTC
Labels: 👀 UI
