### ISSUE TITLE
Fresh install - different counter

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1834] opened 2019-11-25 20:29 UTC
Hello developer,

I got some issues with a fresh install.
There are different post counter: but in fact there are 5 posts:

![memo on MVO Pixelfed](https://user-images.githubusercontent.com/58190287/69575012-c075a500-0fc9-11ea-8a12-2d42085174bf.png)

![MVO Pixelfed](https://user-images.githubusercontent.com/58190287/69575062-d71bfc00-0fc9-11ea-8c25-77dc79ac493d.png)

**Comment by ghost** [comment] 2019-11-25 21:53
Same in fresh install:

![Memo on MVO Pixelfed](https://user-images.githubusercontent.com/58190287/69581146-4bf53300-0fd6-11ea-897f-88e9e5a0ff13.png)


![MVO Pixelfed](https://user-images.githubusercontent.com/58190287/69581149-4e578d00-0fd6-11ea-8ee7-bc5aa1ef19a2.png)

**Comment by ghost** [comment] 2019-11-25 22:07
Link to the profile page: https://pixel.memo-village.online/Memo

**Comment by ghost** [comment] 2019-11-25 22:51
A cronjob 

`sudo systemctl stop pixelfed; cd /home/pixelfed; php artisan cache:clear; sudo systemctl start pixelfed; `

every 10 minutes updates counter on profile page and restarts pixelfed.service.

**Comment by dansup** [comment] 2019-11-26 01:24
@memo-567 This looks like a regression, will investigate!

**Comment by ghost** [comment] 2019-11-26 04:41
Running this cron job sadly resets my mastodon timeline too.

**Comment by dansup** [comment] 2019-11-28 02:21
@memo-567 Fixed in latest commits!

**Closed as completed** 2019-11-28 02:21 UTC

**Comment by ghost** [comment] 2019-11-28 07:07
Works perfect. Thanks.
