### ISSUE TITLE
embed albums 

### ISSUE THREAD

**Issue by arteteco** [pixelfed/pixelfed#328] opened 2018-07-17 10:42 UTC
Hello everyone,

I can't see a function to embed albums on other websites, like flickr doesn. I'd like to have my own instance and to embed album in my website and forums and other places, it would awesome.

Is there something like this already? Maybe an API call I missed?

Otherwise I'd humbly suggest to put it into the todo

Thanks!

**Comment by trwnh** [comment] 2019-03-03 06:15
Duplicate of #776

**Closed as completed by trwnh** 2019-03-03 06:15 UTC
Labels: ➕ Enhancement, 🔃 API, 👀 UI
