### ISSUE TITLE
[Docker] First post looping forever

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#1147] opened 2019-04-17 04:16 UTC
Note: This is on v0.8.6 - I will retest on v0.9.0

Hey, the first "visible" post seems to loop forever. in the main feed and my profile.
This is the same image (notice my post count is 2).

the preview missing from the profile, but that's a different issue 🗡  

<img width="783" alt="image" src="https://user-images.githubusercontent.com/17537000/56260615-76ab0f00-610a-11e9-9dad-71260b3fcdcf.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/17537000/56260630-8591c180-610a-11e9-956c-56631d74f0ac.png">

**Comment by shleeable** [comment] 2019-04-17 06:25
Reproduction:

1) Upload first image again.. do not wait more than 10 seconds.
2) click the home straight away and you'll get the rolling image
3) delete first image

This issue is likely due to the processing period being broken by leaving the page.
1) As my first image, upload something and wait 30 seconds.. 
2) click home and you'll get a single image

the page does not reload... tho

video: https://matrix.org/_matrix/media/v1/download/matrix.org/KKoNwxxxOgPCNzjjlinquakF

**Comment by dadall** [comment] 2019-04-19 14:27
Same error reported to me, without Docker. Fixed by posting a second picture then deleting the looping one.

It's probably a condition used to list the number of available pictures that is failing.

**Comment by dansup** [comment] 2019-04-21 18:42
@Shleeble @dadall Strange, I can't reproduce this locally or on staging or production instances. Can you provide more detailed reproduction steps?

**Comment by shleeable** [comment] 2019-04-22 02:34
https://pixelfed.social/shlee

I replicated in pixelfed.social.. follow the video if it still works

**Comment by dansup** [comment] 2019-04-22 03:08
Fixed in latest commits

**Closed as completed by dansup** 2019-04-22 03:08 UTC
Labels: ⚙️ Deployment
