### ISSUE TITLE
Allow admin to change terms, privacy policy and instance description

### ISSUE THREAD

**Issue by jaranta** [pixelfed/pixelfed#1258] opened 2019-05-03 08:14 UTC
I'm running a hosted instance at pixelfed.fi and noticed that the admin user cannot change the terms, privacy policy or description of the instance. Currently, those are specific to pixelfed.social, e.g. a reference to Canadian jurisdiction.

I would like to customise the policies to match the instance and provide additional information about this specific instance. Changing that information might be possible by editing files on the server, but I do not have command line access to the server.

**Comment by jaranta** [comment] 2019-06-19 07:47
I'd like to emphasize that this is pretty high priority for anyone running a hosted instance. I know legal requirements aren't exactly exciting, but users on my instance are still bound an user agreement referring to Canadian law, which might not even be compatible with Finnish law -- I honestly would rather not find out the hard way.

**Comment by trwnh** [comment] 2019-06-19 08:05
>I'd like to emphasize that this is pretty high priority for anyone running a hosted instance.

FWIW, it's way too early for anyone to be running Pixelfed in a hosted environment. Pixelfed is not ready for production usage. But setting config values from admin dashboard is WIP in any case.

~Duplicate of #1390~

**Comment by trwnh** [comment] 2019-06-19 08:08
Actually nvm, leaving this issue open to track configurable docs and closing the other one instead

**Comment by dansup** [comment] 2019-07-18 05:55
Added in latest commits

**Closed as completed by dansup** 2019-07-18 05:55 UTC
Labels: ➕ Enhancement, 🏛️ Legal
