### ISSUE TITLE
`Delete` does not federate properly

### ISSUE THREAD

**Issue by peelson** [pixelfed/pixelfed#737] opened 2019-01-04 18:49 UTC
Pressing the "Delete" button on a comment doesn't actually delete it, it just hides it from the site.
Actual comment: https://pixelfed.social/p/nosleep/29093
Comment as seen from another instance: https://feminism.lgbt/@nosleep/101359786060409328

**Comment by trwnh** [comment] 2019-01-04 19:24
My guess is that Delete activities are not being federated properly? Because the comment is deleted on the Pixelfed side, but feminism.lgbt has not been made aware of this.

**Comment by dansup** [comment] 2019-01-05 07:35
@peelson @trwnh It appears there is a bug in the comment delete logic, will be fixed in an upcoming commit.

**Comment by trwnh** [comment] 2019-01-16 23:36
This is also happening when you delete regular posts. Cached versions remain on other servers as no `Delete` seems to be sent out.

**Comment by MasterGroosha** [comment] 2019-01-31 07:48
I guess there's no way to really delete a currenty deleted post? I see 404 on pixelfed.social, but have image untouched in Mastodon reading the same pixelfed account.

**Comment by todoneunl** [comment] 2019-02-17 14:35
I can confirm this is still not solved. Using up-to-date code.

**Comment by amal-fi-haq** [comment] 2019-03-03 21:29
Deleting a federated image also does not work. 

I posted a test image from my PixelFed. It federated to my mastodon (which follows my PxelFed).  However, when deleting the image from PxlFd, the image deletion did NOT federate even after 24 hours. On mastodon, I can currently see the deleted PxlFd image... as well as comment left on that image...

**Comment by dansup** [comment] 2019-03-06 02:11
Fixed in #968

**Closed as completed by dansup** 2019-03-06 02:11 UTC
Labels: 🕸️ Federation, ❗❗ Priority: High

**Comment by Geobert** [comment] 2026-05-06 12:51
it’s back https://github.com/VernissageApp/VernissageServer/issues/533
