### ISSUE TITLE
Unable to edit or delete own posts

### ISSUE THREAD

**Issue by gegeweb** [pixelfed/pixelfed#1577] opened 2019-08-08 06:37 UTC
Updated with the latest commit.

Always unable to edit or delete own posts.
There is no buttons / actions on the timeline view or post view as you can see on these screenshots.

Timeline : 

<img width="658" alt="Capture d’écran 2019-08-08 à 08 32 52" src="https://user-images.githubusercontent.com/9108457/62680494-a59a0900-b9b7-11e9-8a52-726bf802efa8.png">

Post : 

<img width="972" alt="Capture d’écran 2019-08-08 à 08 31 43" src="https://user-images.githubusercontent.com/9108457/62680504-aaf75380-b9b7-11e9-9bf9-27a9389b812b.png">

**Comment by gegeweb** [comment] 2019-08-08 06:45
I've disabled Monent.ui for my profile, and I can edit or delete post from the post view.
But I can't edit the caption.

**Comment by raphgilles** [comment] 2019-08-08 19:41
Captions will never be editable. @dansup explained why here : https://github.com/pixelfed/pixelfed/issues/823

**Comment by trwnh** [comment] 2019-08-08 21:35
Well, not "never" anymore, but yes this is a partial duplicate of #823 I think. But there is another part of the issue that deals with deleting posts from Moment UI, which is a duplicate of #1235

**Closed as completed by trwnh** 2019-08-08 21:35 UTC
