### ISSUE TITLE
Instagram import not working no media.json 

### ISSUE THREAD

**Issue by BKLronin** [pixelfed/pixelfed#3747] opened 2022-11-12 10:58 UTC
Hi!

I've exported my isnta acount recently to migrate to pixelfed. It seems meta changed the layout they deliver the files in. There is no `media.json` but a `posts_1.json` in  a subfolder called content. I will attach an example.

I havent seen any settings when exporting but html or json and this is the json output. Renanimg it into media.json didn´t work :P

![grafik](https://user-images.githubusercontent.com/6392076/201470875-a2c7b1e8-a769-4d6c-8b0f-762f2a674f1a.png)

[posts_1.zip](https://github.com/pixelfed/pixelfed/files/9994787/posts_1.zip)

**Comment by teddyber** [comment] 2022-11-14 08:25
same situation here. Maybe Instagram changed the export structure?

**Comment by davetapley** [comment] 2022-11-25 23:21
Dupe of #2877, potential fix on #2751 was closed so maybe add some 👍🏻  there.

**Comment by BKLronin** [comment] 2022-11-26 00:46
Thanks for the reply!

**Closed as not planned** 2024-05-31 05:13 UTC
