### ISSUE TITLE
Private accounts are hidden in web UI but accessible over API and partially via ActivityPub

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1763] opened 2019-10-05 20:51 UTC
@dansup 

Private accounts on the web will display a message and block access

For third party apps, it is able to pull in private posts and display them within the app

**Comment by dansup** [comment] 2019-10-06 02:54
@okpierre Private accounts can make public posts, we are discussing removing the ```public``` scope from private accounts. cc @trwnh 

https://github.com/pixelfed/pixelfed/blob/aa6ebabcd4af1877da1fb57b32d8a0f4de2f11ad/app/Http/Controllers/Api/ApiV1Controller.php#L296

**Comment by trwnh** [comment] 2019-10-06 03:23
OK, did some testing and I see the following on pixelfed.social:

- loading a web page of a private account -> 403, "sorry this action is not allowed"
- requesting activitypub json of a private account -> 200 ok, actor json returned
- requesting activitypub json of a private account's public/unlisted post (if you know its url) -> cloudflare 404 with `{"message": ""}` as response
- can't test api from the browser because it redirects to /login

i think the most consistent thing we can do is at least display the public bits of a private account, since the real privacy is per-post

**Comment by okpierre** [comment] 2019-10-06 04:08
IMHO this is critical to the privacy of accounts

If the account is public, a post is delivered based on user's selection of **EACH** post 

The way I imagine private account is **NOTHING** should be retrieved or sent regardless what users choose for each post

Will that be the solution? Hope to understand this better

**Comment by trwnh** [comment] 2019-10-06 04:11
If you have an unfetchable profile and a public post then you will run into issues.

We could probably do a separate "secure" mode that requires authorization before your profile or any of its posts can be fetched (with the limitation that "public" posts will not work)... but that's different than what should probably be called a "locked" profile (one where followers must be approved. and thus followers-only posts are not just delivered to anyone who asks for them)

As currently written I do agree it's confusing and implies wrong assumptions:
>When your account is private, **only people you approve can see your photos and videos** on pixelfed. Your existing followers won't be affected.

the emphasized bit there is technically only correct via the web ui. coincidentally, it actually goes further, because attempting to load a "private account" will 403, which means *you actually can't follow that profile*, unless you manage to find some other way (e.g. they follow you first? i'm not sure how it arises in practice, but i would call this a regression because it used to be possible to follow "private accounts" at some prior point)

**Comment by mediaformat** [comment] 2020-01-12 03:44
> attempting to load a "private account" will 403, which means _you actually can't follow that profile_

I just came across this, but it actually returned a 404

> unless you manage to find some other way

I found a work-around was to use the follow intent url:
`https://instance.tld/i/intent/follow?user={user}`

EDIT:  ~~It seems the follow didn't go through, I'll test this further.~~ It works!

**Comment by dansup** [comment] 2022-01-23 10:16
Fixed in latest commits!

**Closed as completed by dansup** 2022-01-23 10:16 UTC
Labels: 🕸️ Federation, 🔃 API, 🖐️ UX
