### ISSUE TITLE
White placeholders in overview sites

### ISSUE THREAD

**Issue by Seestern** [pixelfed/pixelfed#940] opened 2019-03-03 12:29 UTC
Sometimes pictures in overview sites - with these square tiles - are not visible. Instead there is a white placeholder for them. If you click on the placeholder you can see the picture.

- This happens when you are logged in or not.
- Refreshing the site has no success.
- The affected pictures seems to be random.

**Comment by trwnh** [comment] 2019-03-03 18:09
Duplicate of #567?

**Closed as completed by trwnh** 2019-03-03 18:09 UTC
