### ISSUE TITLE
Seychelles islands are missing in "Places" on pixelfed.social

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#1705] opened 2019-09-13 21:06 UTC
Instance: https://pixelfed.social

This may sound weird, but I just tried to search for anything related to [Seychelles islands](https://en.wikipedia.org/wiki/Seychelles) in Places and found nothing :(
I tried the following queries: "Seychelles" (overall name), "Mahe", "La-Digue" (main islands), "Victoria" (capital of Mahe island).

I intend to upload some photos from Seychelles after my trip next year, so adding these places would be highly appreciated! Moreover, if you show me where cities list is stored, I'd make a PR in such situations myself.
Thanks in advance!

**Comment by dansup** [comment] 2019-09-13 23:27
@MasterGroosha The cities.json dataset we are using only includes cities with a population of over 5000. The country can be found in the Places directory, https://pixelfed.social/discover/location/country/seychelles.

I know this is not ideal, we're investigating ways to improve Places without relying on 3rd party APIs like Google Maps.

**Comment by MasterGroosha** [comment] 2019-09-14 03:15
This is interesting. I see "Victoria" in your directory with link above, but it seems to be inaccessible via web interface: https://youtu.be/cNVGBcukWtw

**Comment by dansup** [comment] 2019-10-05 06:04
@MasterGroosha can't reproduce, closing this issue. https://pixelfed.social/discover/places/102614/victoria

**Comment by MasterGroosha** [comment] 2019-10-05 06:13
@dansup, unfortunately, the issue isn't solved.

Watch this (since you didn't watch previous video)
https://youtu.be/yR_joT0maFY

You cannot add "Victoria, Seychelles" as geo location for an image. Being listed in Places list doesn't mean this location is available to set.

If you think this is another issue, I'll gladly open a new one myself.

**Closed as completed** 2019-10-07 06:49 UTC

**Comment by dansup** [comment] 2019-10-07 06:55
@MasterGroosha I added a short term fix that increase the amount of results in the search. Long term we will need to order results better based on population size and other factors.

**Comment by MasterGroosha** [comment] 2019-10-07 06:58
@dansup, thank you! Just being possible to access all available places is great!
