### ISSUE TITLE
pixelfed.social Firefox visual issue

### ISSUE THREAD

**Issue by Astuceman** [pixelfed/pixelfed#1091] opened 2019-03-27 11:26 UTC
![Screenshot_2019-03-27 pixelfed](https://user-images.githubusercontent.com/19632209/55071849-f99bf500-5089-11e9-827b-df9765780636.png)

As you can see, in firefox the pictures are too big (have tried without plugins)

In chromium everything is fine

![Capturnbge](https://user-images.githubusercontent.com/19632209/55072093-83e45900-508a-11e9-9528-8a0e1eab3f2d.PNG)

Firefox 66.0.1 64bits
Windows 1809 (17763.379) 64bits

**Comment by asonix** [comment] 2019-03-27 15:18
This happens on my instance, pooltoy.club with Firefox 65.0.1 on Linux as well

**Comment by AlanSanchezP** [comment] 2019-04-02 00:44
I checked quickly the css code, seems like the problem is the usage of css property zoom. 
Changing it to transform: scale(0.66) fixes the size. However, it is incorrectly positioned and I kind of fixed it with transform: translate.

Screenshot from Firefox 66.0.2 on windows 8.1
![imagen](https://user-images.githubusercontent.com/8754996/55368192-2152e900-54e0-11e9-9f63-13f40070dbe8.png)

Code on element inspector:
![imagen](https://user-images.githubusercontent.com/8754996/55368232-52cbb480-54e0-11e9-9adf-16a04021c3b5.png)

I can't submit a PR since I'm not on my development pc (and because this is still hardcoded, didn't test it on different resolutions), sorry, I hope someone else can do it.

**Comment by trwnh** [comment] 2019-04-02 03:58
Duplicate of #1043

**Closed as completed by trwnh** 2019-04-02 03:58 UTC
Labels: 👀 UI
