### ISSUE TITLE
Show Proper Message When Account Is Private Instead Of Error Page

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1765] opened 2019-10-06 04:59 UTC
Currently when visiting a private account, it shows the following error
> Sorry, this page isn't available.

In previous versions, a private account will show message similar to:
> This Account is Private ... Login to see ...

https://github.com/pixelfed/pixelfed/blob/833d17db4e03054414f2b33ec8c2e1235457d486/resources/views/profile/private.blade.php#L22

**Comment by trwnh** [comment] 2019-10-06 05:16
I think we should discuss this on #1763 instead

Duplicate of #1763

**Closed as completed by trwnh** 2019-10-06 05:16 UTC
