### ISSUE TITLE
App login not working when switching users

### ISSUE THREAD

**Issue by hnrd** [pixelfed/pixelfed#4058] opened 2023-01-02 15:15 UTC
Upon login, the app opens a web view, which is already logged in when there's a session in my device's browser.

I want to change accounts, so instead of granting permissions I hit the change user link in the web view, log into the correct account, and get taken to the home timeline, not back to the app authentication screen.

Had to go back to the app, tap log in again and was able to grant permissions to the correct account after.

This is backend behaviour rather than the apps fault, so I open the report here.

**Comment by trwnh** [comment] 2024-06-02 11:08
Duplicate of #4228

**Closed as not planned by trwnh** 2024-06-02 11:08 UTC
