### ISSUE TITLE
Change Instance logo from GUI

### ISSUE THREAD

**Issue by xplosionmind** [pixelfed/pixelfed#2924] opened 2021-09-10 17:04 UTC
Related to #2802, but adding more context:

as of right now, in `Settings > Brand` in the admin GUI interface almost everything about the instance can be changed, except for its icon/logo. It would be nice to add the possibility to do so from the GUI admin interface, too.

Thanks a lot!

**Comment by ghost** [comment] 2021-09-10 20:27
@dansup 

Yes please implement this as and the ability to change the name of main site page which says pixelfed near the logo 

And the back to pixelfed links to back to $site name 

it matters allot for branding !

**Comment by trwnh** [comment] 2022-08-09 14:54
Duplicate of #2802

**Closed as not planned by trwnh** 2022-08-09 14:54 UTC

**Comment by TVHstudio** [comment] 2022-08-29 01:29
doesn't work! i can't find the way to the logo. this panel does not enough to customize index page, seo title ...vv please update it
