### ISSUE TITLE
Check signups against HIBP

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#285] opened 2018-06-17 15:01 UTC
It might be a good idea to check the passwords that users submit for new account registrations against the [pwned passwords](https://haveibeenpwned.com/API/v2#PwnedPasswords) database maintained by Troy Hunt.

The idea is to prevent people from using weak or already compromised passwords when making new accounts. Many large services including 1Password and EVE Online have already implemented this and it seems to be working great for them.

There are already a few different PHP Laravel libraries for doing this, such as [this one](https://github.com/valorin/pwned-validator), so the implementation shouldn't be too hard.

For more information on the pwned passwords system see these blog posts about the service:

https://www.troyhunt.com/pwned-passwords-in-practice-real-world-examples-of-blocking-the-worst-passwords/

https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/

**Comment by dansup** [comment] 2018-06-17 20:06
Duplicate of #41

**Closed as completed by dansup** 2018-06-17 20:06 UTC
