### ISSUE TITLE
Double @ when replying to comment

### ISSUE THREAD

**Issue by dnno** [pixelfed/pixelfed#1652] opened 2019-08-31 09:39 UTC
When replying to a federated reply, a double @ is used and brakes the user reference.See screeshot. 
![Screenshot_20190831-113514](https://user-images.githubusercontent.com/2003552/64062192-f9c59100-cbe3-11e9-8047-590b9f7f7b66.jpg)

**Comment by trwnh** [comment] 2019-08-31 12:56
Duplicate of #1564

**Closed as completed by trwnh** 2019-08-31 12:56 UTC
