### ISSUE TITLE
Remote follow

### ISSUE THREAD

**Issue by kpcyrd** [pixelfed/pixelfed#106] opened 2018-06-01 16:23 UTC
I would like to follow https://pixelfed.social/ansuz but it seems there's no remote follow button yet to follow from mastodon.social :)

**Comment by ansuz** [comment] 2018-06-01 17:29
aww, thanks :heart:

**Comment by kaffeeringe** [comment] 2018-08-21 18:30
When I search for my pixelfed-account from Mastodon: 

1. It shows correctly the number of posts, but followers and following a 0
2. It keeps waiting for the follow-button
3. It doesn't show any of my posts

BTW: Thank you for this great project. I have been waiting for something like this. I wanted to start a semi-anonymous project on Instagram. But Instagram suggested me all kinds of people I know. And I knew my account would be suggested to them. I didn't want that. I wanted to publish some photos, And whoever liked them should watch them. It didn't want a network of my friends there.

**Comment by trwnh** [comment] 2018-08-21 19:27
AP workers haven't all been fully implemented. It's in the works! See #5, #73 for more info; maybe https://pleroma.site/users/pixeldev for updates.

**Comment by dansup** [comment] 2018-09-15 16:45
Duplicate of #5

**Closed as completed by dansup** 2018-09-15 16:45 UTC
