### ISSUE TITLE
Changed email address, now can't log in due to redirect loop

### ISSUE THREAD

**Issue by bgpugh** [pixelfed/pixelfed#1911] opened 2020-01-03 03:48 UTC
Went to my account settings and changed my email address (pixelfed username [bpugh](https://pixelfed.social/bpugh)). I was sent a verification email but it looks like the login redirects are failing. Screenshots attached for both Safari and Firefox on macOS.
<img width="693" alt="Firefox" src="https://user-images.githubusercontent.com/848155/71706237-8356bc80-2d98-11ea-97aa-293e6c956e95.png">
<img width="539" alt="Safari" src="https://user-images.githubusercontent.com/848155/71706238-8356bc80-2d98-11ea-824d-c6cb91673dd5.png">

All navigation to pixelfed.social now results in this (unless I open in Private Browsing or clear all pixelfed storage/cookies) and existing login sessions can't take actions until email address is verified.

**Comment by dansup** [comment] 2020-01-11 05:30
@bgpugh I have manually verified your account, I can't reproduce this bug so I'm going to close this issue.

**Closed as completed by dansup** 2020-01-11 05:30 UTC
