### ISSUE TITLE
PHP 7.3 required?

### ISSUE THREAD

**Issue by jplock** [pixelfed/pixelfed#1575] opened 2019-08-08 01:45 UTC
Is PHP 7.3 required to run Pixelfed or will PHP 7.2 (which ships with Ubuntu 18.04 LTS) work as well?

Running `php composer.phar install`, I get:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/db-dumper 2.14.2 -> satisfiable by spatie/db-dumper[2.14.2].
    - spatie/db-dumper 2.14.2 requires php ^7.3 -> your PHP version (7.2.19) does not satisfy that requirement.
  Problem 2
    - spatie/db-dumper 2.14.2 requires php ^7.3 -> your PHP version (7.2.19) does not satisfy that requirement.
    - spatie/laravel-backup 6.3.1 requires spatie/db-dumper ^2.12 -> satisfiable by spatie/db-dumper[2.14.2].
    - Installation request for spatie/laravel-backup 6.3.1 -> satisfiable by spatie/laravel-backup[6.3.1].
```

**Comment by trwnh** [comment] 2019-08-08 01:48
Duplicate of #1561

**Closed as completed by trwnh** 2019-08-08 01:48 UTC
