### ISSUE TITLE
Notifications on Home Feed does not popup post preview image on hover for 'shared' notifications

### ISSUE THREAD

**Issue by justdaj** [pixelfed/pixelfed#4785] opened 2023-11-21 16:32 UTC
In the Home screen, the Notifications is a box on the right of the screen. When hovering over the word "post" in bold, for a liked notification, a small preview of the post image appears. Doing the same for shared notifications has no preview.  

In the example below, the first notification will who a preview on hover, but the second will not.

v0.11.9, desktop

![Screenshot from 2023-11-21 16-27-01](https://github.com/pixelfed/pixelfed/assets/5741412/7a937381-d581-4e7a-9224-fb09bb1693cc)

**Comment by trwnh** [comment] 2024-06-03 19:36
Duplicate of #4950

**Closed as not planned by trwnh** 2024-06-03 19:36 UTC
