### ISSUE TITLE
Enhancement: Option to view all sensitive posts

### ISSUE THREAD

**Issue by Graycot** [pixelfed/pixelfed#3704] opened 2022-10-17 04:41 UTC
It would be nice to have the option to allow all posts marked sensitive or CW to be visible by default.

**Comment by Casuallynoted** [comment] 2022-11-20 23:50
I also agree, I'd like to have this since I personally don't mind most of the CW on my feed.

**Comment by nhoizey** [comment] 2023-11-01 13:11
I think this is a duplicate of #2462, you could maybe add a 👍 there.

**Closed as not planned** 2024-05-31 05:24 UTC
