### ISSUE TITLE
attributedTo can be an array instead of a string as well

### ISSUE THREAD

**Issue by swentel** [pixelfed/pixelfed#761] opened 2019-01-09 16:07 UTC
statusFirstOrFetch assumes the attributedto property is a string/url. However, this can be an array too which why we currently can't send replies from Bridgy Fed - see https://github.com/snarfed/bridgy-fed/issues/39

See also https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attributedto

**Comment by trwnh** [comment] 2019-07-18 07:13
closing as a functional duplicate of #722

**Closed as completed by trwnh** 2019-07-18 07:13 UTC
