### ISSUE TITLE
Visual Indication For Favourites

### ISSUE THREAD

**Issue by BrainBlasted** [pixelfed/pixelfed#70] opened 2018-06-01 06:48 UTC
Currently when you favourite an image, the heart stays the same color. Since a common pattern is to change the color of already favourited entities in other platforms, I was confused and did a brief like-unlike loop. Perhaps the color could be changed to black when something is already favourited?

**Comment by trwnh** [comment] 2018-06-04 03:29
Seems to be live, albeit with a bug where already-liked posts are unfilled and stuck in reverse of what they should be.

**Comment by trwnh** [comment] 2018-06-04 03:34
Also not indicating on individual posts - only on timeline.

**Comment by dansup** [comment] 2018-06-04 03:35
Fixed in #186 #187 #188

**Comment by BrainBlasted** [comment] 2018-06-13 01:11
@dansup can you reopen this issue? Currently the favourites button no longer changes colors.

**Comment by BrainBlasted** [comment] 2018-06-13 01:12
Aplogies, must have been something on my end.

**Comment by BrainBlasted** [comment] 2018-06-13 01:13
Ah, figured it out. The button is not the proper color if you reload with the image already favourited. Hitting the favourite button again may unfavourite it.

**Comment by trwnh** [comment] 2018-06-13 07:54
@BrainBlasted The current solution to that right now is to run `ls.clear()` in your browser's console, because the cause of the issue is the hydration of likes. Anything you liked before the indicator logic was implemented seems to be reversed as you described.

This will be less and less of an issue for new users, but I have to think that hydrating likes shouldn't cause any issues, and the indicators should be updated at the same time, but idk how all that works.

**Comment by dansup** [comment] 2018-11-22 03:03
Fixed in latest commits!

**Closed as completed by dansup** 2018-11-22 03:03 UTC
Labels: ➕ Enhancement, ❗❗ Priority: High, 👀 UI
