### ISSUE TITLE
Add Ability To Use Passwordless Login

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1632] opened 2019-08-21 19:59 UTC
Imagine using just your username or email address to sign in?

I've posted a video here so hopefully it will be considered for pixelfed
https://mastodon.social/@okpierre/102656748154313613

Moving the World Beyond Passwords
https://fidoalliance.org/fido2/

**Comment by trwnh** [comment] 2019-08-21 23:28
Duplicate of #617

**Closed as completed by trwnh** 2019-08-21 23:28 UTC
Labels: ➕ Enhancement, 🖐️ UX, 🤔 In-Depth
