### ISSUE TITLE
Can't create mixed media post or post with more than one video

### ISSUE THREAD

**Issue by mbliznikova** [pixelfed/pixelfed#4900] opened 2024-02-07 02:47 UTC
Can't create a post with more than 1 video or with mixed media (both photo and video media types in one post).
Getting 400 Bad Request "Must contain a single photo or video or multiple photos" (latest staging and dev branches). 

![Screen Shot 2024-02-06 at 6 39 33 PM](https://github.com/pixelfed/pixelfed/assets/7782090/73b2d05c-34cc-4013-b3d1-b55a37f4e4c2)

**Comment by mbliznikova** [comment] 2024-02-07 03:10
Created the PR with fix #4901

**Comment by trwnh** [comment] 2024-05-31 14:07
Duplicate of #4816

**Closed as not planned by trwnh** 2024-05-31 14:07 UTC
