### ISSUE TITLE
Implement WebSockets/Real-time Streaming API Support

### ISSUE THREAD

**Issue by ciolt** [pixelfed/pixelfed#319] opened 2018-07-06 07:57 UTC
So this is a really cool feature from Mastodon, that not many fediverse servers have. Mastodon supports real-time WebSocket streams (as well as HTTP chunked-encoding streams, but this can be very messy). I'm working with the public streams and it's definitely much better than what, for example, Pleroma is doing by polling the server repeatedly for updates. Updates are also delayed, since everything seems up-to-date until you poll the server again. This uses a lot of data (sending a hundred bytes of HTTP headers/receiving them every few seconds) and is just not ideal. It's wasted internet bandwidth for absolutely no good reason.

I suggest that PixelFed support WebSocket connections, so that way developers (like me!) can start having a lot of fun with it. It could also help with building real-time notifications, timeline updates, push notifications, etc. Overall, it makes for a very smooth and modern experience.

There are a few ways of doing this:

- As far as I know, using a service like [Pusher](https://pusher.com/) is *really convenient* but then you'd have to sign up for an account, and start to pay up after you max out the free account limits. This is not a great solution.

- The other would be to use a PHP library like [Ratchet](http://socketo.me/) to build WebSocket support on PixelFed.

- The Mastodon-ey way of doing it would be to spin up a Node.js server that runs the real-time streams, listens for server-side updates, and relays the data to connected clients. This is the method that Mastodon uses to support streams, it works very well but I'm not sure how well it could work in a PHP environment.

**Comment by dansup** [comment] 2018-07-07 23:37
Hi this is a duplicate of #2

**Closed as completed by dansup** 2018-07-07 23:37 UTC
