### ISSUE TITLE
Support for non-alphabet tags.

### ISSUE THREAD

**Issue by SiegfriedEhret** [pixelfed/pixelfed#466] opened 2018-09-16 02:12 UTC
Hello !

Here is [my post](https://pixelfed.social/p/SiegfriedEhret/13029) where tags are considered normal text:

![97cd688d-5c89-4ca7-bbe3-1d029064940b](https://user-images.githubusercontent.com/537567/45592085-6492a380-b964-11e8-9469-3076736bdebe.png)

And the [same image](https://pixelfed.social/p/SiegfriedEhret/13034) without the `#日本` part where tags are clickable:

![4c3ba920-9074-4355-a67f-505e41f01192](https://user-images.githubusercontent.com/537567/45592161-652c3980-b966-11e8-9ae4-bffb896f4be0.png)

A few notes:

- In the first case, when I go to a hashtag page, my posts are found. [example](https://pixelfed.social/discover/tags/nezu?src=hash).
- https://pixelfed.social/discover/tags/日本?src=hash does not work.

Thanks !

**Comment by trwnh** [comment] 2018-09-16 02:17
Similar to #406 and #415 -- the current hashtag helper converts all tags to the English alphabet, and needs to be overridden.

**Comment by SiegfriedEhret** [comment] 2018-09-16 02:33
Sorry about the duplicate ! It shouldn't break the links and render only text for the valid tags, right ?

**Comment by dansup** [comment] 2018-09-23 03:26
Duplicate of #415

**Closed as completed by dansup** 2018-09-23 03:26 UTC
