### ISSUE TITLE
Instagram cross-posting

### ISSUE THREAD

**Issue by Megver83** [pixelfed/pixelfed#2309] opened 2020-07-06 17:00 UTC
It would be cool to be able to cross-post media from Pixelfed to Instagram, that would make transitioning from IG to PF **much** easier and softer for IG users, aside from avoiding having to go to instagram.com to post. Afaik, Facebook Inc. provides and API for IG, however, I've no idea if that official API works for what I propose here.

Beta stuff (e.g. stories) may be left later, if they become a problem.

**Comment by kojid0** [comment] 2020-07-11 07:27
What about Pixelfed creating a possibility to share the posted photo to instagram with the options to
1) blur the photo slightly
2) place a text "👉🏼new post on pixelfed.social", if possible as a clickable link to the actual content

This would create a slow and soft transitioning process from IG to PF by making friends wanting to know what's going on (blurred photo as a spoiler).

**Comment by trwnh** [comment] 2020-07-11 08:02
Duplicate of #1080

**Closed as completed by trwnh** 2020-07-11 08:02 UTC
