### ISSUE TITLE
Cannot upload avatar for the 1st time

### ISSUE THREAD

**Issue by loicm** [pixelfed/pixelfed#723] opened 2018-12-30 16:14 UTC
On a local fresh Pixelfed install with only one user (me).

When I want to change my avatar it does not work and I have a "404 error page".

Investigating the code from the `AvatarController::store()` method I think I found why.

See: https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Controllers/AvatarController.php#L36

As I have no avatar yet the `firstOrFail()` raise the 404.

- If I should have had an Avatar linked to my profile, the error is elsewhere at account creation
- I suggest to replace `firstOrFail()` by `firstOrNew([])`. So if there is no Avatar a new one is created. I can provide a PR if needed. I have tested the solution on my instance and it's working.

**Comment by Findus23** [comment] 2018-12-30 16:19
That sounds pretty much like the solution for #654 (at least I also had the same error when setting it for the first time)

**Comment by loicm** [comment] 2018-12-30 16:39
Yes it is. I should have had linked to this issue,thanks for having done it 😊

**Comment by dansup** [comment] 2019-01-06 06:33
Duplicate of #654

**Closed as completed by dansup** 2019-01-06 06:33 UTC

**Comment by loicm** [comment] 2019-01-06 08:18
I can understand the duplicate, but what about my solution?
