### ISSUE TITLE
Backdating posts

### ISSUE THREAD

**Issue by hayo** [pixelfed/pixelfed#4558] opened 2023-07-26 11:05 UTC
Since importing from instagram does not work well, a hotfix might be the ability to backdate posts, and import them manually. So add a field datetime field "published on"?

**Comment by paulexyz** [comment] 2023-11-01 23:36
Seems like a simple fix, but i don't think it would be any wise to add such a feature since that can be used in a misleading / fraud kinda way. I'd rather vote for fixing some of the flaws the current implementation of the import has instead.

One that fixed a bunch of them is correctly decoding the brokenly encoded JSON from Facebook/Instagram #4726

**Comment by trwnh** [comment] 2024-05-31 05:23
Duplicate of #2871

**Closed as not planned by trwnh** 2024-05-31 05:23 UTC
