### ISSUE TITLE
Encrypt Direct Messages

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1386] opened 2019-06-10 20:11 UTC
Perhaps another reason to use pixelfed instead of the major networks

Add encryption to direct messages

**Comment by trwnh** [comment] 2019-06-11 03:39
technically any "direct" messages are just that -- direct, like email. and just like email, all parties involved need to be using the same encryption schema.

as far as the current activitypub network is concerned, encryption happens over the wire with https, but it is decrypted once it reaches the inbox. having encrypted messages in your inbox *requires* some sort of key exchange to be done, and this is the part that can't really be standardized easily. theoretically all implementations could just agree to use rsa public keys with pgp, but this needs to be agreed upon and implemented in multiple projects.

also, such an approach would be questionable at best -- since the private keys are stored in the software running on the server, storing the inbox in an encrypted format provides no real security benefit. in other words, the problem is that even though encryption happens between two clients, in our case (and in most monolithic activitypub implementations), the server *is* the client. the only way around this is to outsource key management to the user's local device (which can be extremely inconvenient and also must be synced to each and every device where the user wishes to view their messages). good luck syncing keys across android/ios/windows/macos/linux in a way that is accessible to everyone.

really, we have a couple of options here:

- option one, we break up our monolithic instances into a true client-server design. this requires all users to import private keys from local storage, on every device they want to use pixelfed. pixelfed apps would need to sync their keys to every single device, somehow, or else the user is responsible for key management and sync. (really difficult)
- option two, we make it easier to self-host pixelfed/etc so that users don't have to trust someone else with their data. the user is free to manage their storage however they want. messages would only reach their recipients.
- or option zero, we let users do whatever they want over-the-top like email/pgp, or sending ciphertext via dm to be decrypted externally, etc.

**Comment by okpierre** [comment] 2019-06-11 04:02
Thanks for sharing details @trwnh  

What about encryption between members/admin within instance? Would that be better and helpful?

**Comment by dansup** [comment] 2019-06-16 05:44
They are called Direct Messages for a reason. The UX of encrypted private messages is out of scope.

**Closed as completed by dansup** 2019-06-16 05:44 UTC
Labels: ❌ Won't Fix
