### ISSUE TITLE
Mentions wrong rendered

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#4107] opened 2023-01-20 10:44 UTC
I posted an image on my pixelfed. Then i commented this posting on my friendica and mentioned a user from a mastodon-instance.

Going back to pixelfed the comment shows the mentioning from the mastodon-user, but the link is wrong.

This is the posting https://japix.schuerz.at/p/jakob/521707129977851734
The User "wuffel" should be from social.tchncs.de, but the link in the mention is https://japix.schuerz.at/@wuffel?src=rpp 

I tried to verify this bug with another user in pixelfeds matrix channel. 
He got the right link to the user on social.tchncs.de on his first try in desktop-mode. I got a wrong link, which suggests wuffel is a user on my friendica-account  (it was this link, pixelfed showed me: https://japix.schuerz.at/i/web/username/wuffel@soc.schuerz.at), then the other user tried it in smartphone-view, and then the mention-link got rendered (and saved in database?) to a user on my pixelfed-instance, as shown above.

So it could be a problem with rendering and saving in smartphone-view/size.

**Comment by trwnh** [comment] 2024-06-03 19:45
Duplicate of #3641

**Closed as not planned by trwnh** 2024-06-03 19:45 UTC
