### ISSUE TITLE
When I like a post it should jump back to the post (non-JS)

### ISSUE THREAD

**Issue by faissaloo** [pixelfed/pixelfed#179] opened 2018-06-03 14:46 UTC
If I'm like halfway down my timeline I don't want to have to scroll back.

**Comment by dansup** [comment] 2018-06-03 20:00
Duplicate of #87

**Comment by faissaloo** [comment] 2018-06-03 20:55
This isn't a duplicate, this can be implemented without any Javascript at all, just by having those buttons link to the current page with a # followed by the id of the element to jump to.

**Comment by trwnh** [comment] 2018-06-04 03:18
Yeah, using section anchors (applying an #id to an element) is probably the best way to do it. You don't need JS if you do it in PHP. Assign each post a random dynamic anchor id and upon refreshing the page, load that anchor.

**Comment by trwnh** [comment] 2019-03-02 22:16
Old non-JS frontend has been deprecated for Vue-enabled frontend; a new non-JS frontend will be implemented later

**Closed as completed by trwnh** 2019-03-02 22:16 UTC
Labels: ➕ Enhancement, 👀 UI
