### ISSUE TITLE
Impossible to change one picture on a post.

### ISSUE THREAD

**Issue by MBalensi** [pixelfed/pixelfed#2672] opened 2021-02-20 15:06 UTC
I tried to create a post with several pictures. One of them was not uploaded correctly, so I tried to delete or replace it. I did not find any way to do this, the only things I could edit on this picture were the description and the filter. To delete it, I had to delete the whole post, with all the other pictures in it.
It would be nice to be able to change, delete or add a picture to an existing post.

**Comment by trwnh** [comment] 2021-02-21 01:48
Duplicate of #823

**Closed as completed by trwnh** 2021-02-21 01:48 UTC
