### ISSUE TITLE
The "gallery counter" got no fixed layout position.

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1096] opened 2019-03-30 12:16 UTC
If the gallery contains upright images and landscape format images, the "gallery counter" jumps around an does not stay at the same position in the layout as you can see here:

![Bildschirmfoto 2019-03-30 um 13 03 47](https://user-images.githubusercontent.com/10457918/55275985-d07b9e80-52ed-11e9-8a9a-57ab35a3ba58.png)

![Bildschirmfoto 2019-03-30 um 13 04 00](https://user-images.githubusercontent.com/10457918/55275986-d5405280-52ed-11e9-9dd9-9f72f4daab90.png)

It was tested on [https://pixelfed.de](https://pixelfed.de) today.

**Comment by trwnh** [comment] 2019-03-30 16:32
Duplicate of #796

**Closed as completed by trwnh** 2019-03-30 16:32 UTC

**Comment by trwnh** [comment] 2019-03-30 16:34
Duplicate of #267
