### ISSUE TITLE
iframe for single posts and profiles

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1553] opened 2019-07-27 14:07 UTC
Hello,

Do you plan to make publications and profiles integrable ? For example we should integrate our Pixelfed posts or our users profiles on our blog with an iframe.

Thank you !

**Comment by dansup** [comment] 2019-07-28 04:01
@raphgilles This is being worked on! Duplicate of #776

**Closed as completed by dansup** 2019-07-28 04:01 UTC
