### ISSUE TITLE
Improve Terms of Use

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#1465] opened 2019-06-25 22:27 UTC
The current Terms of Use was created using a free ToS generator. It is too vague. It does not set guidelines for acceptable or unacceptable behavior.

Ideas:
- Add Rules # 1 and # 4 from [Mastodon's Server Covenant](https://joinmastodon.org/covenant)
- Community feedback on potential new rules
- Add rules from the [Code of Conduct](https://github.com/pixelfed/pixelfed/blob/dev/CODE_OF_CONDUCT.md#our-standards)

If you have any suggestions, feel free to reply with them!

**Comment by mkljczk** [comment] 2019-06-25 22:42
These rules from Mastodon Server Covenant are actually about admins’ responsibility and I don’t really think terms of use should adhere to them

**Comment by ealgase** [comment] 2019-06-26 01:17
Shouldn't this be the responsibility of each instance, instead of making the issue in the main project repo?  Because some instances may want different ToS's.

**Comment by trwnh** [comment] 2019-06-26 03:05
#1059, #1060

**Comment by mkljczk** [comment] 2019-06-26 06:01
>Shouldn't this be the responsibility of each instance, instead of making the issue in the main project repo?

It’s good to have default one…

**Comment by dansup** [comment] 2019-06-30 06:15
Added in 68ff420699b8e37428efd8708e38ec609e7a7310

**Comment by jmorahan** [comment] 2019-06-30 13:00
#1059 and #1060 were both closed in favour of this, but they were specifically about the [Terms of Use](https://github.com/pixelfed/pixelfed/blob/dev/resources/views/site/terms.blade.php) and the referenced fix seems to be only for the [Community Guidelines](https://github.com/pixelfed/pixelfed/blob/dev/resources/views/site/help/community-guidelines.blade.php)?

**Comment by chlorinatedsugar** [comment] 2019-08-14 07:40
> #1059 and #1060 were both closed in favour of this, but they were specifically about the [Terms of Use](https://github.com/pixelfed/pixelfed/blob/dev/resources/views/site/terms.blade.php) and the referenced fix seems to be only for the [Community Guidelines](https://github.com/pixelfed/pixelfed/blob/dev/resources/views/site/help/community-guidelines.blade.php)?

I personally think it might indeed be a good idea to keep both #1059 and #1060 open, as they both address separate problems with the Terms of Service, and this "superseding" issue doesn't address either of those explicitly. I haven't been very active in the past few months, but I have noticed that the ToS hasn't been improved in the mean time, despite the issues being high-priority. As it currently stands, the Terms of Service are actually _legally conflicting_ (not just "vague"), and users are _signing away the copyrights of their own content_ by using the software as is. To me, that is a dealbreaker, and has prevented me from uploading content to Pixelfed instances (all of which haven't bothered to alter the ToS in any way).

Now, I am no legal expert, but if you would like me to, I would be willing to change the existing Terms of Service to resolve the mentioned issues and make it respect the user's rights. It is very urgent, any further improvements to the Terms of Service should not delay fixing the issues at hand.

As for the proposed "Community Guidelines" from the linked Code of Conduct and Mastodon Server Covenant, I think they should not be mixed with the Terms of Use. Many of the topics are about social interaction and that makes enforcement ambiguous. Since the Terms of Service are made as a _contract_, they are meant to be legally binding (and may lead Pixelfed or an instance into a lawsuit if breached, you don't want that). Community Guidelines are merely guidelines open to rather broad interpretation, which is required for socially complex situations such as conflicting values and rights. They're part of what's known as "soft law" (see [this link](http://www.annamsw.eu/news/117-on-the-legal-status-of-guidelines.html) for a quick reference). Instead, the Terms of Service should declare that the instance reserves the right to revoke access to users in case of violation of the Community Guidelines.

For the same reasons, I am not sure adding rule # 4 of the [Mastodon Server Covenant](https://joinmastodon.org/covenant) to the Terms of Service is the best idea. Although it seems like a nice-to-have, making it legally binding can have some nasty side effects. Small servers may not have the funds to keep a server running for an additional three months once they realize they don't have enough money, nor the expertise to change the Terms of Service for their instance. In that case, users may file a lawsuit against them, which is detrimental to these small instances. I think one month is a more reasonable number, as that'll still leave enough time to download the user data as well as short enough for small servers to reasonably support. In any case, if this rule enters the Terms of Service in any shape or form, people who run an instance should be clearly informed of the very real legal consequences (accidentally) breaching these Terms will have.

Remember, the Terms of Service isn't just some guideline document, it's a _legal contract_ with severe consequences in case something weird is in it.

**Comment by dansup** [comment] 2019-08-15 00:04
As @chlorinatedsugar has pointed out, we'll need to address our current Terms of Use (related #1059 and #1060) as soon as possible.

**Comment by chlorinatedsugar** [comment] 2019-08-15 14:21
I think it's useful to start with the definition list first. When it comes to the license, no definition is given to "Pixelfed". What does "Pixelfed" refer to? It could refer to a _corporation_, the _software/product_, or the _hosting instance_ running the software. Throughout the [Terms of Use](https://pixelfed.social/site/terms), it seems to refer to "Pixelfed" as a corporation, although the info page [Open Source](https://pixelfed.social/site/open-source) says explicitly that "Pixelfed" is the software.

Which one of the two should be adhered to? I think "Pixelfed" meaning the software would be most clear, as that's how it's promoted everywhere, but something like "Pixelfed's Software" would also do. In the first case, what name does the corporation have? If they have the same name, it must receive some disambiguation.

The hosting instance should also receive a consistent name, I think just going for the full domain name is most clear (e.g. either consistently "pixelfed.social" or consistently "https://pixelfed.social").

**Why this is important**
Currently, the Terms of Use assumes that the hosting instance is owned by "Pixelfed" (which could mean _the software_ according to [this](https://pixelfed.social/site/open-source), not the creators or instance owners), whereas it would make more sense to have the hosting instance be owned by its respective owners (which aren't necessarily the creators of Pixelfed). Therefore, I think the disclaimers and limitations should aim to protect the hosting instance explicitly, as the creators of Pixelfed are already protected by the [AGPL license](https://github.com/pixelfed/pixelfed/blob/dev/LICENSE) (e.g. section 15 and 16). For this to happen, proper definitions must be put in place.

What do you all think?

**Comment by trwnh** [comment] 2019-08-17 07:05
i agree that a proper ToS would apply to the service, not the software. the software equivalent to a ToS is the license, which is agpl. so it should default to filling in the instance's domain name

stuff like this is exactly why the existing ToS should be scrapped entirely -- using a ToS generator will give you incorrect language all over the place, because pixelfed is not a corporate product hosted on a single centralized domain.

**Closed as completed** 2020-01-23 07:17 UTC
Labels: 🏛️ Legal, ❗❗ Priority: High

**Comment by madpipeline** [comment] 2025-09-05 12:54
I don't know how this got resolved, or if this is a regression but https://pixelfed.social/site/terms still forbids in Section 2.a.iii `attempt to decompile or reverse engineer any software contained on Pixelfed's website;`, this being one of the issues reported in #1059, which was superseded by this issue.
