### ISSUE TITLE
Indicate when there is no caption

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1320] opened 2019-05-31 04:58 UTC
It looks odd having username just sitting in space at the bottom of photo

Would it be better not showing username when there's no comment?

**Comment by okpierre** [comment] 2019-06-04 00:33
@trwnh here's a screen capture to show what's happening. 

you mentioned **indicate when there is no caption** so will that mean user will get a message blocking submit unless caption is included?

![pixelfed-no-caption](https://user-images.githubusercontent.com/1679025/58842929-52fe4280-863e-11e9-8631-fe0a214643fe.png)

**Comment by trwnh** [comment] 2019-06-04 00:55
The behavior of displaying username twice is inherited from Instagram. The
header bar shows the original poster, but the pane below that shows caption
and comments. If there is no caption, the username will be shown alone.

By "indicate when there is no caption", I mean that we should probably put
a placeholder that says [no caption] to indicate this.

Alternatively, a redesign may remove the distinction between the header bar
and the rest of the card.

**Comment by trwnh** [comment] 2019-06-04 06:53
Ahh, just realized this is a duplicate of #240

**Closed as completed by trwnh** 2019-06-04 06:53 UTC
Labels: 💭 Suggestion
