### ISSUE TITLE
External authentication

### ISSUE THREAD

**Issue by emersion** [pixelfed/pixelfed#2390] opened 2020-08-24 22:31 UTC
When installing PixelFed for an existing organization, it might be desirable to use an existing external service to handle authentication. That way users can login with their organization account instead of having to register.

This is typically achieved by adding support for OAuth2 or LDAP (e.g. [GitLab has this feature](https://docs.gitlab.com/ee/administration/auth/)).

Would that be something that PixelFed would be open to support?

**Comment by trwnh** [comment] 2020-08-26 04:44
Duplicate of #2089

**Closed as completed by trwnh** 2020-08-26 04:44 UTC
