### ISSUE TITLE
Please add full screen view

### ISSUE THREAD

**Issue by todoneunl** [pixelfed/pixelfed#1172] opened 2019-04-22 14:41 UTC
According issue #159 full screen (using a lightbox view) should be implemented. Unfortunately the image is barely enlarged (in the Moments UI even a bit smaller). 

Can you please add near and/or real full screen? For a image service this is very important IMO.

**Comment by trwnh** [comment] 2019-04-22 22:30
Duplicate of #1017

**Closed as completed by trwnh** 2019-04-22 22:30 UTC
