### ISSUE TITLE
Remote Follower Failure

### ISSUE THREAD

**Issue by WillowMist** [pixelfed/pixelfed#2708] opened 2021-03-22 01:33 UTC
It appears that if someone on another instance (Mastodon in this case) tries to follow a pixelfed user, and has the same username as the user being followed,  Pixelfed will fail with a Duplciate Key error.

Would it be possible to use the entire user address as the key, rather than just the local username?

`

PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "profiles_domain_username_unique"
--
DETAIL: Key (domain, username)=(mastodon.online, @willowmist@mastodon.online) already exists. in /var/www/vhosts/fedi.bub.org/pixelfed.fedi.bub.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115

`

**Comment by inga-lovinde** [comment] 2021-04-04 17:57
It is probably a duplicate of #2520 , and is caused by your username on mastodon containing uppercase letters ("WillowMist").

According to the error message, the entire user address (plus the instance name) is used as a key anyway.

**Comment by ledyba** [comment] 2021-06-21 00:10
I also faced this issue. I can resolve with these step:

 - Remove all data.
 - Enable all these ActivityPub related variables ***before*** running `php artisan instance:actor`.
   - ACTIVITY_PUB=true
   - AP_REMOTE_FOLLOW=true
   - AP_SHAREDINBOX=true
   - AP_INBOX=true
   - AP_OUTBOX=true
   - ATOM_FEEDS=true
   - NODEINFO=true
   - WEBFINGER=true
 - Then run `php artisan instance:actor`.

If these variables are enabled ***after*** creating instance actor, it looks pixelfed doesn't return actor data (JSON-LD) at `https://pixelfed.example.com/users/user_name` correctly.

Please try thise command. This must output json-ld, not HTML.
```bash
curl -H 'Accept: application/activity+json' 'https://pixelfed.example.com/users/user_name'
```

**Comment by ghost** [comment] 2022-05-08 14:46
@ledyba Thanks for the input - I was searching for a similar issue but your answer helped me to fix mine :-) !

**Comment by trwnh** [comment] 2023-01-27 07:54
hmm, the stated fix doesn't seem to be ideal -- enabling activitypub should probably be done before creating the instance actor, sure, but the order in which this is done shouldn't have any effect on processing remote accounts as long as activitypub was enabled. regardless, i'm going to close this specific issue for now until/unless a more specific and reproducible case appears. in such a case, to reproduce we'd need at minimum:

- the remote profile's id
- the local profile's id
- a stack trace including the specific error
- the actions leading up to the error, and any specific steps taken

**Closed as completed by trwnh** 2023-01-27 07:54 UTC
