### ISSUE TITLE
Make it possible to add a global/default license

### ISSUE THREAD

**Issue by lhirlimann** [pixelfed/pixelfed#1542] opened 2019-07-22 13:00 UTC
I'd like a setting where I can set a default license. When I post a picture have a default license checkbox for the default license or the ability to set a different one.

**Comment by okpierre** [comment] 2019-07-22 19:27
Duplicate of https://github.com/pixelfed/pixelfed/issues/13 ?

**Comment by dansup** [comment] 2019-10-05 04:26
We do not plan on adding a default license, in the future you may be able to set a specific license per post.

**Closed as completed by dansup** 2019-10-05 04:26 UTC
