### ISSUE TITLE
Permit login with account number.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [pixelfed/pixelfed#4848] opened 2024-01-04 19:29 UTC
The e-mail address on my account may change, so I'd like to be able to login with my user number rather than the e-mail address so that my credential manager need not reflect the current e-mail address in use.

**Comment by mitexleo** [comment] 2024-01-06 11:07
You meant "username" ?

+1

**Comment by roke-julian-lockhart** [comment] 2024-01-06 14:11
https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879638751

No, @mitexleo, the account number.

**Comment by roke-julian-lockhart** [comment] 2024-01-06 14:17
> https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879638751

Does no issue exist also for the username? ~~If not, I'll make one and link it here for you, because that should be possible too.~~

https://github.com/pixelfed/pixelfed/issues/4852

**Comment by dansup** [comment] 2024-01-06 18:29
Duplicate of #494

**Closed as not planned by dansup** 2024-01-06 18:29 UTC

**Comment by roke-julian-lockhart** [comment] 2024-01-06 19:20
> https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879776453

@dansup, this isn't a duplicate of that issue. They're about entirely different attributes. Regardless, https://github.com/pixelfed/pixelfed/issues/4852#issuecomment-1879794277.

**Comment by s0mt0x64** [comment] 2024-01-07 08:16
> > https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879776453
> 
> @dansup, this isn't a duplicate of that issue. They're about entirely different attributes. Regardless, https://github.com/pixelfed/pixelfed/issues/4852#issuecomment-1879794277.

Take meds
