### ISSUE TITLE
Support MariaDB

### ISSUE THREAD

**Issue by MrPetovan** [pixelfed/pixelfed#132] opened 2018-06-02 02:44 UTC
Follow-up to #107 

I pulled the fix for it, ran `artisan migrate:fresh` again, 

got 

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timest
  amp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `statuses` (`id` bigint unsigned not null auto_increment primary key, `uri` varchar(191) null, `caption` varchar(191) null, `rendered` text nu
  ll, `profile_id` bigint unsigned null, `in_reply_to_id` bigint unsigned null, `reblog_of_id` bigint unsigned null, `url` varchar(191) null, `is_nsfw` tinyint(1) not null default '0', `visibility` enum('public', 'unlisted',
  'private', 'direct') not null default 'public', `reply` tinyint(1) not null default '0', `likes_count` bigint unsigned not null default '0', `reblogs_count` bigint unsigned not null default '0', `language` varchar(191) null
  , `conversation_id` bigint unsigned null, `local` tinyint(1) not null default '1', `application_id` bigint unsigned null, `in_reply_to_profile_id` bigint unsigned null, `entities` json null, `created_at` timestamp null, `up
  dated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

Turns out there's no `json` field type on 
```
mysqld  Ver 10.1.26-MariaDB-0+deb9u1 for debian-linux-gnu on x86_64 (Debian 9.1)
```

**Comment by dansup** [comment] 2018-06-02 03:53
@MrPetovan Yes, a work around will be to detect mariadb and change the json() and jsonb() schema to use TEXT instead of JSON or JSONB. This is a framework level change.

**Comment by dansup** [comment] 2018-06-02 04:20
@MrPetovan A quick hack is to change /vendor/laravel/framework/src/Illuminate/database/Schema/[Blueprint.php](https://github.com/illuminate/database/blob/9a3ca4c43fc18b21d5093f2e99a907fcaf3886c4/Schema/Blueprint.php#L845)

```php
return $this->addColumn('json', $column);
```

to 

```php
return $this->addColumn('text', $column);
```

You should never change files in the /vendor directory because they will be updated on the next `composer update` so I need a long term fix.

**Comment by MrPetovan** [comment] 2018-06-02 12:20
Thanks, it's a hack needed for the migration anyway, not for normal operation.

**Comment by MrPetovan** [comment] 2018-06-02 13:22
The hack was enough to go forward with `artisan migrate:fresh`!

**Comment by MrPetovan** [comment] 2018-10-15 18:46
Hi, ahead of the official release, I found this to support the Laravel JSON type with MariaDB: https://github.com/ybr-nx/laravel-mariadb

**Comment by MrPetovan** [comment] 2018-12-25 07:42
Any chance for this to be included at any point in the future?

**Comment by trwnh** [comment] 2019-03-02 22:18
Duplicate of #775 retroactively

**Closed as completed by trwnh** 2019-03-02 22:18 UTC
Labels: ➕ Enhancement, 🔧 Compatibility, ❗ Priority: Mid
