### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#4970] opened 2024-03-04 00:06 UTC
When i search for a hashtag and pixelfed finds postings, i can see the overview.
![grafik](https://github.com/pixelfed/pixelfed/assets/5894829/c93d716e-8f70-4b76-8273-d193c39d3195)
But when i click to an image i can not see the image
![grafik](https://github.com/pixelfed/pixelfed/assets/5894829/cafbe8ae-9fc2-48ea-9d3a-ea3eab8583ba)
The console in browser shows me
![grafik](https://github.com/pixelfed/pixelfed/assets/5894829/7633bc31-78ad-4a1c-b8db-048fc88ecbc7)
`TypeError: t.status.liked_by is undefined`
When i reload page (with F5) i can see the image too
![grafik](https://github.com/pixelfed/pixelfed/assets/5894829/d69a1565-41a5-45ed-8ac3-f645f5373de9)
The browser-console only shows this then:
![grafik](https://github.com/pixelfed/pixelfed/assets/5894829/0f2d55e3-bc67-4e23-9505-33e0c6a9bf2b)

**Comment by mamarguerat** [comment] 2024-03-04 11:06
Seems a duplicate of #4386

**Comment by xundeenergie** [comment] 2024-03-05 14:54
Yes, it's duplicate.
And it duplicates also https://github.com/pixelfed/pixelfed/issues/4605

**Closed as completed** 2024-05-31 14:04 UTC
