### ISSUE TITLE
Horizon not enabled by default in Docker deployments

### ISSUE THREAD

**Issue by johackim** [pixelfed/pixelfed#1026] opened 2019-03-13 18:17 UTC
Hello, 

Thanks for this project !

I launched my pixelfed instance but previews are not displayed.

![](https://i.imgur.com/Qaandbf.png)

**Comment by trwnh** [comment] 2019-03-13 18:38
Did you upload a video or a GIF? The thumbnail generator currently only works on static image types.

**Comment by johackim** [comment] 2019-03-13 18:49
Hello @trwnh,

No just png or jpeg images

**Comment by trwnh** [comment] 2019-03-13 18:52
Can you post a link to your profile?

**Comment by johackim** [comment] 2019-03-13 18:53
@trwnh 

https://instagram.ston3o.me/ston3o

**Comment by trwnh** [comment] 2019-03-13 19:00
Did you upload via the Classic or the Experimental uploader?

**Comment by ston3o** [comment] 2019-03-13 19:02
I tested both

**Comment by johackim** [comment] 2019-03-13 19:02
@trwnh I tested both

**Comment by trwnh** [comment] 2019-03-13 19:04
Were you uploading really big pictures?

**Comment by johackim** [comment] 2019-03-13 19:07
@trwnh I tested images ranging from 330K to 2M

**Comment by trwnh** [comment] 2019-03-13 19:11
Hmm. The only thing I noticed while trying to load your image posts was that some of them were not loading instantly, so that's why I suspected size had something to do with it.

More interestingly, I have just managed to reproduce this on pixelfed.social by uploading a 13583 x 5417 image, which generated no thumbnail. So what was the resolution of the photos you were uploading? Data size is not really important, I think it has to do with the dimensions.

**Comment by johackim** [comment] 2019-03-13 19:14
@trwnh  I uploaded images from 615x615 pixels to 4952x3446

**Comment by trwnh** [comment] 2019-03-13 19:21
OK, the big image I uploaded just had its thumbnail generated after some time. So it looks like your instance is not running the thumbnail generator task in the background, for some reason.

**Comment by johackim** [comment] 2019-03-13 19:25
Oh thanks @trwnh , in fact, horizon it's not enable by default with docker environment, when I launch `php artisan horizon` command, it's works ! Thanks @trwnh !

**Comment by trwnh** [comment] 2019-03-13 19:30
Glad to hear you figured out the cause! Reopening this issue to track changes to Docker deployment scripts.

**Comment by dansup** [comment] 2019-03-17 07:59
Fixed in latest commits!

**Closed as completed by dansup** 2019-03-17 07:59 UTC
Labels: ⚙️ Deployment
