### ISSUE TITLE
Import from Instagram - no media.json in the package

### ISSUE THREAD

**Issue by tardar** [pixelfed/pixelfed#3807] opened 2022-11-19 22:26 UTC
Hey guys,

i try actually the instagram import and i can't file a photo directory or a media.json.

Does the json has been renamed ?

The photo directory was located on another name.

Thanks alot :)

**Comment by davetapley** [comment] 2022-11-25 23:21
Dupe of #2877, potential fix on #2751 was closed so maybe add some 👍🏻  there.

**Closed as not planned** 2024-05-31 05:13 UTC
