### ISSUE TITLE
Blank Screen After Install

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2001] opened 2020-02-12 03:46 UTC
Tried out the latest version and getting a blank screen
Went back to previous version and it's fine

Here's what it looks like
![pixelfed-blank](https://user-images.githubusercontent.com/1679025/74301131-0b2cd080-4d20-11ea-9c0f-5f74b2f08026.png)

**Comment by dansup** [comment] 2020-02-12 04:05
@okpierre I can't reproduce on a fresh installation. Are you sure you ran all the commands?

**Comment by okpierre** [comment] 2020-02-12 05:06
@dansup should've mentioned I had v0.10.8 in the folder prior the latest install overwriting so not completely fresh. switched back to v.0.10.8 and blank screen went away

**Comment by okpierre** [comment] 2020-02-13 04:47
@dansup please see links with same issue 

`https://pixelfed.fr/p/cheyenne/43659623462473728`
`https://travelpandas.xyz/p/oufmilo/100545318235541504`
`https://piconic.co/p/sturmen/133226748115554304`

**Comment by dansup** [comment] 2020-02-13 07:08
Fixed in #2006

**Closed as completed by dansup** 2020-02-13 07:08 UTC
Labels: ❗❗ Priority: High
