### ISSUE TITLE
Profile images dosnt load on S3 #3843 not solved

### ISSUE THREAD

**Issue by ehsan0921** [pixelfed/pixelfed#3845] opened 2022-11-28 03:42 UTC
@dansup 
still have the same problem.
did exactly as you mentioned.
I have the latest version and useing cloudron.
would appreciate if you could help.

Best

**Comment by okpierre** [comment] 2022-11-28 07:17
Yes correct @ehsan0921 many of us are still having this issue even with new installs

The problem is `return config('app.url')` which is added to the URL

Will submit a pull request for @dansup to review so it can be available for everyone in the next update

**Comment by ehsan0921** [comment] 2022-11-28 07:20
thanks mate.

**Comment by ehsan0921** [comment] 2022-11-28 07:23
> Yes correct @ehsan0921 many of us are still having this issue even with new installs
> 
> The problem is `return config('app.url')` which is added to the URL
> 
> Will submit a pull request for @dansup to review so it can be available for everyone in the next update

just I was wondering how https://pixelfed.social works well.
I notice the profile image is uploading on the main server but the posts are uploading on S3.
do you have any idea about that?

**Comment by okpierre** [comment] 2022-11-28 07:27
> thanks mate.

You're welcome! I've been reporting bugs with the project since the beginning and we all want Pixelfed to succeed but all the bugs are scaring users away

**Comment by dansup** [comment] 2022-11-28 07:49
@ehsan0921 @okpierre Make sure you don't have `AWS_URL` set in .env, and if `PF_ENABLE_CLOUD=false` you can use `REMOTE_AVATARS=true` to store them locally (otherwise with PF_ENABLE_CLOUD they are stored on cloud fs).

Remember to run `php artisan config:cache && php artisan cache:clear` after editing .env.

@okpierre This isn't a bug, this is a configuration issue, if you notice the OP mentions how these are working properly on pixelfed.social

**Comment by dansup** [comment] 2022-11-28 07:50
Also, make sure you update to the latest `dev` branch commits!

A fix for this was pushed 10 days ago in https://github.com/pixelfed/pixelfed/commit/989e42497aec88ce9f738fdc45acc4f00028c94b

**Comment by dansup** [comment] 2022-11-28 08:19
@ehsan0921 @okpierre Last suggestion, make sure you keep `FILESYSTEM_DRIVER="local"`, changing this will break things. We have `FILESYSTEM_CLOUD` for a reason, and it supports `FILESYSTEM_CLOUD="s3"` or `FILESYSTEM_CLOUD="spaces"`

**Comment by ehsan0921** [comment] 2022-11-28 08:42
@dansup 
thanks for your response. I did as you mentioned but still have problem.
I installed it from cloudron. how to upload those update PHP file in cloudron?
it is the latest version and I did everything as you said but still a problem.


PF_ENABLE_CLOUD=true
REMOTE_AVATARS=true
FILESYSTEM_DRIVER="local"
FILESYSTEM_CLOUD="s3"


AWS_ACCESS_KEY_ID=*****
AWS_SECRET_ACCESS_KEY=*******
AWS_DEFAULT_REGION=ap-southeast-2
AWS_BUCKET=austsocial


when I put the FILESYSTEM_DRIVER="local" then everything goes to local it works but only upload in my server, not S3

**Comment by dansup** [comment] 2022-11-28 08:43
@ehsan0921 Local account avatars are stored locally regardless of S3 or not, I'm working on local avatar S3 support!

**Comment by ehsan0921** [comment] 2022-11-28 08:46
> @ehsan0921 Local account avatars are stored locally regardless of S3 or not, I'm working on local avatar S3 support!

@dansup ok I'm happy to store the Avatar locally.
just want to show the avatar.
I think my configuration has some issue.
would be happy if you could help.
I think others also set the FILESYSTEM_DRIVER=s3 sa well.
because as we change it to local, then all the posts goes to local.

best regards

**Comment by okpierre** [comment] 2022-11-28 09:00
@ehsan0921 can you verify **image path** (not avatar path) when using `FILESYSTEM_DRIVER="local"` it will save me from starting another instance to test

when I set `FILESYSTEM_DRIVER="local"` and all the other settings as suggested the post image url path still goes to 
`https://example.com/storage/m/_v2/xx/xxx/xxx/xxx.png`

for avatar if you want a temp fix https://github.com/pixelfed/pixelfed/pull/3846

**Comment by ehsan0921** [comment] 2022-11-28 10:35
> @ehsan0921 can you verify **image path** (not avatar path) when using `FILESYSTEM_DRIVER="local"` it will save me from starting another instance to test
> 
> when I set `FILESYSTEM_DRIVER="local"` and all the other settings as suggested the post image url path still goes to `https://example.com/storage/m/_v2/xx/xxx/xxx/xxx.png`
> 
> for avatar if you want a temp fix #3846

this is path of one of the images
https://aust.social/storage/m/_v2/502125722834407425/a48ad3dc0-89cf68/pGSmFOoxRHMn/CUco4kBF0h8JPXNAMKtSsDFNWQ4OBKLC5ulxNeUk.png?v=1669631638

and this is the env

PF_ENABLE_CLOUD=true
REMOTE_AVATARS=false
FILESYSTEM_DRIVER="local"
FILESYSTEM_CLOUD="s3"


AWS_ACCESS_KEY_ID=********************
AWS_SECRET_ACCESS_KEY=*********************
AWS_DEFAULT_REGION=ap-southeast-2
AWS_BUCKET=austsocial

**Comment by okpierre** [comment] 2022-11-28 11:56
Sadly it's showing local storage. Same problem as everyone else. 

Thanks for confirming mate!

**Comment by ehsan0921** [comment] 2022-11-28 12:00
> Sadly it's showing local storage. Same problem as everyone else.
> 
> Thanks for confirming mate!

Cheers mate

Just one thing. When do we expect an update? Especially for cloudron?

**Comment by ehsan0921** [comment] 2022-11-29 03:52
by the way guys @okpierre @dansup 
I did the same update on PHP file and now it is fine, Thank you

only with these setting

REMOTE_AVATARS=true
PF_ENABLE_CLOUD=true
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3

I know that @dansup said it is not correct, but I want to upload everything to the cloud.
my question is can I have it FILESYSTEM_DRIVER=s3 for now until the next update? or if I do that after the next update I'll lose everything?

best regards

**Comment by mitexleo** [comment] 2022-11-30 06:13
> by the way guys @okpierre @dansup I did the same update on PHP file and now it is fine, Thank you
> 
> only with these setting
> 
> REMOTE_AVATARS=true PF_ENABLE_CLOUD=true FILESYSTEM_DRIVER=s3 FILESYSTEM_CLOUD=s3
> 
> I know that @dansup said it is not correct, but I want to upload everything to the cloud. my question is can I have it FILESYSTEM_DRIVER=s3 for now until the next update? or if I do that after the next update I'll lose everything?
> 
> best regards

Setting FILESYSTEM_DRIVER to s3 will cause Profile Pics not working  issue ...

**Comment by mitexleo** [comment] 2022-11-30 06:14
The way Pixelfed works is , Every file first uploaded to the local storage... after processing pixelfed will store them in s3 ... But currently pixelfed doesn't remove local files automatically... 

@dansup

**Closed as completed** 2022-11-30 06:14 UTC

**Comment by ehsan0921** [comment] 2022-11-30 06:17
> 

ooooh
so how we should control the space of the server?
how to find the files to delete?
are they in a specific folder @mitexleo ?

**Comment by jdaviescoates** [comment] 2023-01-22 15:43
> But currently pixelfed doesn't remove local files automatically...

Is that really (still?) the case?

I've got ``MEDIA_DELETE_LOCAL_AFTER_CLOUD=true`` in my ``env.production`` and one would guess/ presume that that is about deleting local media once it's been moved to the cloud, no?

Edit: it does indeed seem to be the case, so I've filed a bug report about that here #4114
