### ISSUE TITLE
Preview of animated GIFs missing

### ISSUE THREAD

**Issue by encarsia** [pixelfed/pixelfed#1121] opened 2019-04-04 16:50 UTC
Hi,

preview images of animated GIFs are not generated - or not always or it used to work (see attached screenshot, animated GIF files are circled red).

This affects the
  * profile page (see screenshot below)
  * atom/rss feed
  * remote follow view (at least from Mastodon, link to file is provided)

It would be great if a preview image was provided for feeds and remote followers.

Cheers,

![Bildschirmfoto zu 2019-04-04 18-35-46](https://user-images.githubusercontent.com/16634394/55573015-3199dc80-5709-11e9-8c07-6e128692bee0.jpg)

**Comment by trwnh** [comment] 2019-04-05 02:21
Duplicate of #567

**Closed as completed by trwnh** 2019-04-05 02:21 UTC
