### ISSUE TITLE
Formatting descriptions

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#4078] opened 2023-01-11 13:12 UTC
Hello,

I'm pretty annoyed by the unability to format image descriptions. I wanted to make a description on multiple lines, but they are published on only one line. I think a formatting with html or markdown could help solving this.

**Comment by jim-easterbrook** [comment] 2023-01-28 15:01
Have you tried including `\n` characters in your text? I've found this works when posting media to pixelfed using the Mastodon.py package.

**Comment by trwnh** [comment] 2024-06-03 19:46
Duplicate of #3821

**Closed as not planned by trwnh** 2024-06-03 19:46 UTC
