### ISSUE TITLE
Feature Request: Full Export of Post Data

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4550] opened 2023-07-18 12:09 UTC
Currently, the export function limits exports to 500 posts or shares. It would be nice to be able to export an entire account for both archival purposes and to migrate if we want to move to another service. Removing the 500 post limit would be amazing.

**Comment by pcmhatre** [comment] 2023-08-20 18:11
Any reason for this limitation? Especially now after the ability to import Instagram photos, me as a new user already have 500+ posts.

**Comment by kr428** [comment] 2023-09-01 13:14
Interested to see that, too, at the very least for personal backup reasons.

**Comment by bergentroll** [comment] 2024-01-11 09:04
Until it is not implemented, there is an option [to download data with API](https://gitlab.com/bergentroll/pixelfeeder/-/tree/main?ref_type=heads#backup-command), post-by-post. It is not the way to migrate data transparently, but at least a way to not to lost images when an instance will become unavailable.

**Comment by kr428** [comment] 2024-01-11 13:32
> Until it is not implemented, there is an option [to download data with API](https://gitlab.com/bergentroll/pixelfeeder/-/tree/main?ref_type=heads#backup-command), post-by-post. It is not the way to migrate data transparently, but at least a way to not to lost images when an instance will become unavailable.

Neat, will look into that. It uses authenticated API not "just" public access as far as I can tell? I've been hacking stuff like this with python locally too, for a while, but at some point stopped lacking time (and the fact that I missed some non-public posts this way...).

**Comment by bergentroll** [comment] 2024-01-12 07:24
> It uses authenticated API

Yes, and so should see user's private posts. But it seems not a topic for this conversation. ☺️

**Comment by trwnh** [comment] 2024-05-31 05:17
Duplicate of #814

**Closed as not planned by trwnh** 2024-05-31 05:17 UTC
