### ISSUE TITLE
Support for hosted instances

### ISSUE THREAD

**Issue by jaranta** [pixelfed/pixelfed#1431] opened 2019-06-19 07:44 UTC
Currently administration requires changing files on the server (at least `.env`, required for contact email), which is not possible on a hosted instance. Supporting instance hosting is important, because it allows people who can't do the technical administration themselves to run an instance. Instead of requiring changes to local files, these changes should be available from an admin interface.

Related: https://github.com/pixelfed/pixelfed/issues/1258

**Comment by trwnh** [comment] 2019-06-19 08:08
Duplicate of #1390

**Closed as completed by trwnh** 2019-06-19 08:08 UTC
