### ISSUE TITLE
Number of posts is reported wrong, count is off

### ISSUE THREAD

**Issue by martonlente** [pixelfed/pixelfed#4948] opened 2024-02-19 17:50 UTC
Hello,

I noticed that the number of posts is reported wrong. I've just 3 posts in my Posts, and 3 posts in my Archive. It should either be 3 (if archived posts are included), or 6 (if archived posts are not included). The current number, 4 is off.

Screenshot:
![Screenshot_20240219_184148](https://github.com/pixelfed/pixelfed/assets/8543884/8a655398-52fe-44be-ab81-c476abcd1bda)

Steps:
1. I created three posts. Number of posts was fine.
2. I archived the three posts.
3. I recreated the three posts as new posts (I made some tweaks to images' crop). Number of posts went off, it showed 5 total.
4. As a test, I unarchived, and rearchived the three archived posts to try if it resolves the problem. Number of posts went down to 4 total, which is weird.

You can check the above on my newly-opened account: https://pixelfed.social/i/web/profile/653362380958743115

Thank you.

**Comment by yo-scottie-oh** [comment] 2024-03-14 16:24
@martonlente is this a duplicate of #4727?

**Closed as not planned** 2024-05-31 04:54 UTC

**Comment by martonlente** [comment] 2024-05-31 10:40
The posts count display still consistently shows a wrong value. @trwnh why is a fix _not planned_? Is there maybe something wrong on the account level? Thanks for the explanation!

**Comment by trwnh** [comment] 2024-05-31 13:29
The issue was closed as stale/duplicate but Github shows all of this under the umbrella of "not planned". See #5115 after I am done cross-linking issues.
