### ISSUE TITLE
Error 500 at Pixelfed.social instance (SQLSTATE[22003]: Numeric value out of range)

### ISSUE THREAD

**Issue by ivanmendoza** [pixelfed/pixelfed#3539] opened 2022-06-11 20:07 UTC
## Describe the bug
I tried to unfollow a user, at Pixelfed.social instance, and I got an error message ("Oops! An error occurred when attempting to unfollow this account."). 

Looking for more information at _Console_ I found this response:

```mysql
SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`forge`.`profiles`.`following_count` - 1)' (SQL: update `profiles` set `following_count` = `following_count` - 1, `profiles`.`updated_at` = 2022-06-08 22:11:19 where `id` = 434409099228093267 and `profiles`.`deleted_at` is null)
```
**Endpoint**: `https://pixelfed.social/api/v1/accounts/425429608383714567/unfollow`

## Steps to reproduce
1. Signup/Login into a pixelfed.social account. 
2. Follow the @JoeyDeruy@mastodon.art account. 
3. Later, try to unfollow that user.

## Expected behavior
* Unfollow any user that I want without error.

## Screenshots
![Screenshot of Pixelfed error message](https://user-images.githubusercontent.com/911905/173203246-ecc906b6-d455-4e87-90a3-6b5142b64b55.png)

## Additional notes

* I tried to unfollow the user from many ways (profile, popover card, desktop, mobile, different browsers, etc.)

**Comment by MrAn0nym** [comment] 2022-06-12 16:02
Can confirm

One way you can still unsubscribe is using the old UI (https://pixelfed.social/{username}?fs=1 as this uses another route

**Comment by dansup** [comment] 2022-06-13 08:46
I can't reproduce this, can you try this again on pixelfed.social?

**Comment by ivanmendoza** [comment] 2022-06-13 16:03
> One way you can still unsubscribe is using the old UI...

Can't use the old UI. For some reason, the old UI just works for feed principal (homepage) and I can't unfollow a user from there.

> I can't reproduce this, can you try this again on pixelfed.social?

Still happening. I recorded a small video to show you the issue

https://user-images.githubusercontent.com/911905/173395424-aa8c8f89-12cf-4819-8537-6abc8f4273f1.mp4

**Comment by MrAn0nym** [comment] 2022-06-17 16:54
> > One way you can still unsubscribe is using the old UI...
> 
> Can't use the old UI. For some reason, the old UI just works for feed principal (homepage) and I can't unfollow a user from there.

Use the link to access the old UI for profiles (https://pixelfed.social/{username}?fs=1)

(Or just open it via this menu)
![image](https://user-images.githubusercontent.com/63542658/174342912-da6e8e19-9449-4a12-aab8-0779029648fb.png)

**Comment by jessienab** [comment] 2022-07-20 14:55
Still an issue, and I can workaround it by using the ?fs=1 suggestion per the above.
However to do so, you have to manually copy the account name, as when using the new UI, it will auto-change to the profile ID.

I too could not change to the old UI to unfollow, but once in the old UI with ?fs=1, unfollowing had no issues.

Here's an example link I used to unfollow, with the given HTTP 500 response.
I passed the link using a curl prompt, but realistically the response is the same in browser as from curl.

> https://pixelfed.social/api/v1/accounts/255864065535119360/unfollow
> 
> {"error":"SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`forge`.`profiles`.`following_count` - 1)' (SQL: update `profiles` set `following_count` = `following_count` - 1, `profiles`.`updated_at` = 2022-07-18 18:47:26 where `id` = 286886570496233472 and `profiles`.`deleted_at` is null)"}

This was all done on pixelfed.social

**Comment by MrAn0nym** [comment] 2022-07-22 09:04
@jasonnab Can you try to follow the account again and check if unfollowing now works as expected?
After using the workaround i was no longer able to reproduce this behavior


**Probable cause of the error:**
The error is most likely caused by a wrong `following_count` value, probably introduced by a now fixed bug. 
When the following_count is 0 (but you're actually following someone) and then use the unfollow endpoint `\`following_count\` - 1` returns a negative (and thus invalid) value


**Possible solutions are:**
a) Recalculating the follow_count or every user
> (Probably the better one)

b) Adding additional checks when unfollowing which prevent negative follow_counts
> (Could lead to other problems in the future as it would only fix the db when unfollowing everyone)

**Comment by jessienab** [comment] 2022-07-26 08:05
> @jasonnab Can you try to follow the account again and check if unfollowing now works as expected? After using the workaround i was no longer able to reproduce this behavior

@MrAn0nym 
Unfortunately I'm still getting a 500 error trying to unfollow :(

The profile I'm testing: https://pixelfed.social/i/web/profile/255864065535119360
(However this issue happens with any account)

I refollowed, 200 OK. Attempt to unfollow, 500 Error, and response:

> {"error":"SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`forge`.`profiles`.`following_count` - 1)' (SQL: update `profiles` set `following_count` = `following_count` - 1, `profiles`.`updated_at` = 2022-07-26 07:55:58 where `id` = 286886570496233472 and `profiles`.`deleted_at` is null)"}

**Comment by MrAn0nym** [comment] 2022-07-26 08:29
@jasonnab 
You started following using the old UI, right?
(endpoint `https://pixelfed.social/i/follow`)

From my testing it seems that this /\ endpoint doesn't update the following count, the `/api/v1` however does
e.g (`https://pixelfed.social/api/v1/accounts/255864065535119360/follow`)

**Comment by jessienab** [comment] 2022-07-26 08:58
> @jasonnab You started following using the old UI, right? (endpoint `https://pixelfed.social/i/follow`)

Have now tested two ways:

* Go to https://pixelfed.social/Digitographer?fs=1, follow
* Go to https://pixelfed.social/i/web/profile/255864065535119360, unfollow: same error.

Doing a follow and unfollow through the old UI exclusively works no problem. Oddly, it seems that on the old UI, clicking the follow or "unfollow" button simply sends the same "follow" request to the API. I guess if the account is followed, it unfollows, and if not it follows...

Also on the old UI, it may show to "follow" the account even if it's already being followed, but the hover text will show unfollow.

Perhaps another thing to look at, that the new UI is sending an unfollow request? Just spitballing ideas! :+1:

**Comment by MrAn0nym** [comment] 2022-07-26 11:43
Can you try (both) following and unfollowing on the new UI?
(Believe i found the issue)

**Closed as completed** 2022-08-02 01:06 UTC

**Comment by dansup** [comment] 2022-08-02 01:09
Fixed in 44de1ad! This was caused by trying to decrement the `following_count` of `0` causing the `out of range` error, if you still experience this issue after updating, feel free to re-open this.

**Comment by jessienab** [comment] 2022-08-04 19:30
Hey, sorry for a late reply. Thank you so much @dansup and @MrAn0nym , confirmed working with no issues; on Web UI 2 and using PixelDroid ;)

I'm sure a lot of other people really appreciate the efforts too! :)

**Comment by MrAn0nym** [comment] 2022-08-07 18:42
> Fixed in https://github.com/pixelfed/pixelfed/commit/44de1ad74878b4c6c4c067e4713110c84db2386d!

Yes and no xD. The problem is/was that the following count isn't incremented when using the old UI
followers_count isn't as well iirc

**Comment by MrAn0nym** [comment] 2022-08-07 18:48
Fixed in https://github.com/pixelfed/pixelfed/commit/44de1ad74878b4c6c4c067e4713110c84db2386d!

Yes and no xD. The problem is that the following count isn't incremented when using the old UI
followers_count isn't as well iirc

**Comment by MrAn0nym** [comment] 2022-08-07 18:49
Can someone reopen the issue and rename it to e.g.
>Following count isn't incremented in old UI
