### ISSUE TITLE
License for photos

### ISSUE THREAD

**Issue by kaffeeringe** [pixelfed/pixelfed#400] opened 2018-08-21 08:43 UTC
Hej,
It would be great if I could select a creative commons license for each image - like at Flickr.

**Comment by dansup** [comment] 2018-08-21 21:54
Duplicate of #13

**Closed as completed by dansup** 2018-08-21 21:54 UTC

**Comment by ghost** [comment] 2020-08-15 20:38
So finally was this implemented? So can I specify the license? 
Since, I would like to pick a service like that. Do you know any alternative to Flickr - where I can specify license?
