### ISSUE TITLE
Private accounts never send an Accept Follow

### ISSUE THREAD

**Issue by dermike** [pixelfed/pixelfed#1594] opened 2019-08-12 08:14 UTC
In #5, this is checked "Follow approved: Accept Follow should be delivered to their inbox to let them know the follow was successful",
but doesn't seem to work in practice between Pixelfed and Mastodon. Mastodon is still waiting for follow request to be accepted after accepting on private Pixelfed account.

**Comment by trwnh** [comment] 2019-10-09 04:03
Is this still happening?

**Comment by dermike** [comment] 2019-10-09 05:15
@trwnh Yes (Mastodon 3.0 and Pixelfed 0.10.6)

**Comment by trwnh** [comment] 2019-10-09 05:23
OK, just reproduced

**Comment by trwnh** [comment] 2019-10-09 05:32
So here's Inbox, but this bit is part of the "else" clause (i.e., if the account is not private, handle the follow then send the Accept): https://github.com/pixelfed/pixelfed/blob/f9f94f6dca9c18a3f4ea6eb440ad575721be7e32/app/Util/ActivityPub/Inbox.php#L193-L208

So the reason why Outgoing Accept Follow is checked in #5 is that it *is* done... for public accounts.

It seems that the follow request is actually being handled up here for private accounts: https://github.com/pixelfed/pixelfed/blob/f9f94f6dca9c18a3f4ea6eb440ad575721be7e32/app/Util/ActivityPub/Inbox.php#L166-L171

But the AccountController doesn't handle remote follow requests any differently than local ones yet... https://github.com/pixelfed/pixelfed/blob/c563beecdd2ab75b460e6368f42b025b8aa85fd8/app/Http/Controllers/AccountController.php#L331-L358

This is what the database table for follow requests looks like, according to dan
![](https://d1sz9tkli0lfjq.cloudfront.net/items/3O1e2V411e3v3B1A313Q/Screen%20Shot%202019-10-09%20at%2012.23.41%20AM.png)

So I think checking for `is_local` and then dispatching an Accept Follow delivery should fix this, and maybe add the appropriate method for that check to the model https://github.com/pixelfed/pixelfed/blob/dev/app/FollowRequest.php

**Comment by lapineige** [comment] 2020-06-28 15:55
Hello,

Any update on this topic ?
It makes the use of private account nearly impossible for some people :(

**Comment by igormcoelho** [comment] 2022-05-10 13:45
In my case, I have a private account and I can only accept a follower in Old UI... then I come back to New UI for general usage. It's annoying, hope this is fixed soon. Anyway, congratulations for the nice software.
By the way, my instance (pixelfed.social) in NewUI only shows "[Powered by Pixelfed](https://pixelfed.org/)" on bottom... It would be very useful to display the version (that's why I cannot say which version number is affected here).

**Comment by dansup** [comment] 2024-01-03 10:46
Fixed in the latest commits!

**Closed as completed by dansup** 2024-01-03 10:46 UTC
Labels: 🕸️ Federation, ❗❗ Priority: High
