### ISSUE TITLE
posting multiple images

### ISSUE THREAD

**Issue by bong0** [pixelfed/pixelfed#427] opened 2018-09-01 08:51 UTC
I'm trying to upload multiple images in one post, but only the first one is shown/editable although the hint text indicated multiple images should be possible "Limited to 6 photos per post."

* Browser: Vivaldi 1.15.1147.64 (latest), Safari (latest), Chrome (latest)
* OS: macOS 10.13.6 (latest)
* instance: pixelfed.social

EDIT: The upload seems to work well since all images are contained in the post when submitting. The issue is that **just the first one is displayed**.

![multiimage](https://user-images.githubusercontent.com/179111/44944280-465d6d00-add4-11e8-8163-e3a266eea913.gif)

**Comment by orithena** [comment] 2018-09-18 17:33
Adding to that: On Firefox mobile (latest), I can't even select multiple images. The image picker that is being called (on a Huawei P10 phone with EMUI 5.1) seems not to provide this functionality. Trying to pick multiple images one after the other (using the browse button multiple times) results in only the last image being selected and uploaded.

**Comment by trwnh** [comment] 2018-09-20 10:25
Related to #171 and specifically this comment: https://github.com/pixelfed/pixelfed/issues/171#issuecomment-397224719

It has nothing to do with browser, pretty sure, so it doesn't need the `browser compatibility` tag @dansup

**Comment by orithena** [comment] 2018-09-20 10:40
Adding to my comment: Even with an image picker that superficially supports picking multiple images, only one image is uploaded. (Firefox Mobile/EMUI 5.1/Android 7/Google Photo Image Picker)

**Comment by dansup** [comment] 2018-09-23 03:31
Duplicate of #171

**Closed as completed by dansup** 2018-09-23 03:31 UTC
