### ISSUE TITLE
Image orientation not detected in compose UI

### ISSUE THREAD

**Issue by muesli** [pixelfed/pixelfed#1068] opened 2019-03-23 02:44 UTC
Trying to upload portrait photos, the orientation doesn't get correctly detected and they're displayed as landscape both in the "Create Post" dialog as well as on the feed once uploaded.

**Comment by dansup** [comment] 2019-03-24 18:33
@muesli We need more information, what instance was this on? If it was on your instance, is horizon running? Are you sure the exif data contains the proper orientation?

**Comment by muesli** [comment] 2019-03-24 19:15
Sorry, should have mentioned that: this is on pixelfed.social.

From EXIF:
"Image Orientation: 6"

Also, Mastodon correctly identifies the image orientation.

**Comment by MasterGroosha** [comment] 2019-03-25 12:59
Can confirm. I should also note that using "rotate" in any image viewer in Windows and then rotating back makes Pixelfed.Social show correct orientation for uploaded photo.

**Comment by FanchTheSystem** [comment] 2019-05-22 08:01
any news on this ?

**Comment by muesli** [comment] 2019-07-18 06:13
@dansup Does that mean this has gotten fixed recently?

**Comment by muesli** [comment] 2019-07-18 06:15
Just a heads up, tried it again and still not working on pixelfed.social.

**Comment by trwnh** [comment] 2019-07-18 06:26
Can you provide an example of a photo that gets uploaded with the incorrect rotation?

**Comment by muesli** [comment] 2019-07-18 07:08
![dsc00551](https://user-images.githubusercontent.com/146378/61436543-51ad7e80-a93b-11e9-8858-fe6f7a922316.jpg)

![image](https://user-images.githubusercontent.com/146378/61436460-26c32a80-a93b-11e9-979b-00e000f6bbb6.png)

**Comment by muesli** [comment] 2019-07-18 07:09
Great, of course GitHub fails at rotating the image, too :laughing:

Regardless of that, any photo viewer, instagram, flickr or Mastodon will correctly render the photo, respecting the provided EXIF Orientation information.

Edit: Click the upper photo and your browser will also correctly render the original file. I guess GitHub just strips the EXIF headers from the thumbnail.

**Comment by trwnh** [comment] 2019-07-18 07:23
![image](https://user-images.githubusercontent.com/10606431/61437574-12fbd200-a903-11e9-9cde-0c4d33caa872.png)

Cannot reproduce

**Comment by trwnh** [comment] 2019-07-18 07:29
OK, I think I managed to reproduce somewhat...

- Clicking the image to load the full size shows correct orientation
  - File manager shows correct orientation
  - Compose box shows correct orientation
  - Final post shows correct orientation

- Saving the thumbnail directly...
  - File manager shows correct orientation
  - Compose box shows **incorrect** orientation
  - Final post shows correct orientation

So that image is only incorrect on Github and in the compose UI. Weird...

**Comment by muesli** [comment] 2019-07-18 07:30
Well, what can I say? It seems to be working for me now, too, which makes me think pixelfed.social just got updated?

Glad I provided a screenshot of what was happening for me until a few minutes ago on pixelfed.social in the comment above, otherwise I'd doubt my own sanity now :laughing:

**Comment by trwnh** [comment] 2019-07-18 07:33
It may also be a browser thing? https://phiffer.org/etc/exif-orientation-test/

**Comment by muesli** [comment] 2019-07-18 07:33
Uhm... no. It's only working sometimes. This is hella confusing. Tried the next photo from the set and it's showing up incorrectly again. (I think I may have opened the photo of the old man in a photo viewer that adjusted the orientation "silently")

![dsc00567](https://user-images.githubusercontent.com/146378/61438119-06956a80-a93f-11e9-93e9-aba273c265af.jpg)

**Comment by muesli** [comment] 2019-07-18 07:36
Also a heads up: even when it's showing up correctly, the filters of the image show a stretched version of it.

**Comment by trwnh** [comment] 2019-07-18 07:48
~the weird stretch is a regression (i distinctly remember fixing that bug in the past).~ but i'm not sure what's going on with the EXIF. again, it *only* has the wrong rotation in the preview and on Github thumbnails. 

direct download | thumbnail download
--- | ---
![test](https://user-images.githubusercontent.com/10606431/61439040-63286380-a906-11e9-9740-a6bfc7993177.jpg) | ![test2](https://user-images.githubusercontent.com/10606431/61439038-63286380-a906-11e9-8091-f243c76dd7d8.jpg)
![image](https://user-images.githubusercontent.com/10606431/61439185-a71b6880-a906-11e9-9a57-3d1029eae0d5.png) | ![image](https://user-images.githubusercontent.com/10606431/61439192-af73a380-a906-11e9-9058-b25008baced0.png)
![image](https://user-images.githubusercontent.com/10606431/61439975-23627b80-a908-11e9-8a84-6cbccfc39097.png) | ![image](https://user-images.githubusercontent.com/10606431/61440003-307f6a80-a908-11e9-83e2-b472e1351125.png)

**Comment by trwnh** [comment] 2019-07-18 07:57
One other weird thing is that the "Orientation" seems to be set properly, but the Maker Notes includes two entries for "Rotation"...

![image](https://user-images.githubusercontent.com/10606431/61439502-43de0600-a907-11e9-956f-9f996efd94b1.png)

![image](https://user-images.githubusercontent.com/10606431/61439667-8d2e5580-a907-11e9-9933-ac1f80cdd192.png)

**Comment by trwnh** [comment] 2019-07-18 07:59
Also in Chrome I can get both the correct and incorrect rotations (depending on whether I downloaded the thumbnail or direct link).

**Comment by trwnh** [comment] 2019-07-18 08:02
At any rate, I feel like this is happening only in the Compose UI so I've reopened it and changed the title for now.

**Comment by jacotec** [comment] 2019-07-18 18:05
I gave Pixelfed a try today, set it up and it looks very promising. But this bug is the first "No-Go" yet which I've discovered with my first test post ;-)

Uploaded 4 Photos directly from my iPhone, having my Pixelfed site open in Safari. The orientation is shown correctly on the iPhone!

But on other Browsers (MAC/Safari, MAC/Chrome) one is correct, two are lying "on the side" as already shown here before, one is "head over" 180° wrong. It seems the orientation information seems not to be recognized by Pixelfed.

Also when I click "edit" on my post in the browser view, I can't see the pictures, every picture space shows just "No Preview Available".

**Comment by varjolintu** [comment] 2019-10-05 13:40
I'm also having this problem. A raw picture from iPhone, and its orientation is detected by macOS QuickLook and Preview (plus other software). Uploading the image to Pixelfed fails to detect the correct orientation. The image is always turned 90 CCW.

**Comment by dansup** [comment] 2020-04-14 04:44
I'm going to close this issue as the latest ComposeUI is able to rotate the image before posting the status! 

<hr>

<img width="647" alt="Screen Shot 2020-04-13 at 10 42 03 PM" src="https://user-images.githubusercontent.com/877217/79186921-224b7580-7dd8-11ea-81aa-d91df77fb5be.png">
<img width="650" alt="Screen Shot 2020-04-13 at 10 42 33 PM" src="https://user-images.githubusercontent.com/877217/79186933-27102980-7dd8-11ea-9a0e-f34c0499c244.png">

**Closed as completed by dansup** 2020-04-14 04:44 UTC
Labels: 👀 UI, 🧠 Backend

**Comment by MasterGroosha** [comment] 2020-05-09 00:26
@dansup Unfortunately, this is not a solution.
![изображение](https://user-images.githubusercontent.com/2780044/81458722-934a3700-91a4-11ea-9dad-9b43d09b4b24.png)

Here is the same image. The [left one](https://pixelfed.social/p/Groosha/164529944318316544) was rotated in Pixelfed. In this case I cannot rotate without cropping. 16:9 mode allows only horizontal rectange, not vertical, so that most of the image is lost. The closest option is 1:1 crop, but that's obviously not a solution.

The [image on the right](https://pixelfed.social/) was rotated using some Windows image viewer (any viewer, honestly).

Please re-open the issue. ComposeUI is worse than rotating before upload, unfortunately.

**Comment by MasterGroosha** [comment] 2020-05-09 00:29
![изображение](https://user-images.githubusercontent.com/2780044/81458812-2edba780-91a5-11ea-84a4-18b285a49886.png)

At least a cropping rectange can be fixed by making it switch from "horizontal" to "vertical" regardless of rotation angle (90, 180, 270...)
