### ISSUE TITLE
Arrows to browse picture set not visible on images in portrait format

### ISSUE THREAD

**Issue by fihu** [pixelfed/pixelfed#1045] opened 2019-03-18 08:41 UTC
The arrows to browse next/last image in a set are white and not visible on a white background, e.g. when the image is in portrait format.

See https://pixelfed.social/p/fihu/41111

**Comment by trwnh** [comment] 2019-03-18 14:46
Duplicate of #267, #796

**Closed as completed by trwnh** 2019-03-18 14:46 UTC
