### ISSUE TITLE
Fetch avatars for remote follows

### ISSUE THREAD

**Issue by johnchidgey** [pixelfed/pixelfed#1629] opened 2019-08-20 09:58 UTC
Remote followers currently use the default avatar and don't appear to fetch the actual users avatar from the remote instance.

**Comment by okpierre** [comment] 2020-01-29 04:04
Noticed default avatar is showing for both remote followers and remote following

**Comment by Casuallynoted** [comment] 2021-06-09 17:22
Same, would love to see remote follow avatars come through. Would really make the experience more cohesive across instances imo.

**Comment by Casuallynoted** [comment] 2022-01-10 07:08
Noticed in the latest release it is listed that remote avatars download even when S3 is not enabled (super excited to have this!). I can see this is the case for other Pixelfed instances, but not Mastodon and other such instances. Is this currently intended behaviour?

**Comment by melroy89** [comment] 2023-06-28 18:48
@dansup It seems that Pixelfed is not returning the avatar in the webfinger call: https://pixelfed.social/.well-known/webfinger?resource=acct:dansup@pixelfed.social

Basically adding an additional link with in the JSON body: `{"rel":"http://webfinger.net/rel/avatar","href":"https://domain.com/location/to/image.jpg"}` should solves this problem.

Hence no avatar image is now getting retrieved at the moment, see: https://kbin.melroy.org/u/@dansup@pixelfed.social

**Comment by dansup** [comment] 2024-01-03 11:13
Fixed in the latest commits!

@melroy89 I just shipped the avatar attribute in webfinger ([bca2484](https://github.com/pixelfed/pixelfed/pull/4847/commits/bca248499417963d3e859b46de88fe9ca1aba3d0))

**Closed as completed by dansup** 2024-01-03 11:13 UTC
Labels: 🕸️ Federation, 🧠 Backend

**Comment by melroy89** [comment] 2024-01-03 12:00
> Fixed in the latest commits!
> 
> @melroy89 I just shipped the avatar attribute in webfinger ([bca2484](https://github.com/pixelfed/pixelfed/pull/4847/commits/bca248499417963d3e859b46de88fe9ca1aba3d0))

Great, thank you so much Daniel.
