### ISSUE TITLE
GIF preview not showing on trending pages.

### ISSUE THREAD

**Issue by filippodb** [pixelfed/pixelfed#3619] opened 2022-08-12 14:26 UTC
My GIF animation is here:

https://pixelfed.uno/i/web/post/463349801741693003

on trending page it show a: "No preview available":

https://pixelfed.uno/i/web/discover

![immagine](https://user-images.githubusercontent.com/7091176/184374495-8a96d547-8658-4f34-8195-9a5a7e2d1e69.png)

**Comment by trwnh** [comment] 2024-05-31 00:54
Duplicate of #567

**Closed as not planned by trwnh** 2024-05-31 00:54 UTC
