### ISSUE TITLE
Photos With Different Sizes Jump Around

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1346] opened 2019-06-04 05:33 UTC
When viewing a multi photo post with different sizes, each one will appear to shift around inside the box view

Example:
in a post of four photos, first two vertical and then two horizontal photos, photo no3 and photo no4 will appear to jump down from the corner

**Comment by trwnh** [comment] 2019-06-04 06:58
Duplicate of #267

**Closed as completed by trwnh** 2019-06-04 06:58 UTC
