### ISSUE TITLE
Attempt to upload multiple photos fails silently

### ISSUE THREAD

**Issue by ricardojmendez** [pixelfed/pixelfed#1024] opened 2019-03-13 10:13 UTC
Tested on pixelfed.social just now.

- Selected 6 images to upload - only the first image shows up on the preview, which appears to be a known issue/desired behavior;
- Entered a caption;
- Submitted;

After a while, I got redirected to my profile page, which is empty. There doesn't seem to have been any uploads. There were no error messages on the console or anywhere else.

Reproduced this thrice in a row, to ensure that the console logs weren't being lost.

**Comment by trwnh** [comment] 2019-03-13 16:45
Are you using the Classic uploader or the Experimental one? And can you tell us what your username is on pixelfed.social?

**Comment by dansup** [comment] 2019-03-13 20:32
@ricardojmendez The most likely explanation is that one or more photos are larger than the file size limit, or was an unsupported mime type.

**Comment by ricardojmendez** [comment] 2019-03-13 20:37
@dansup Seems unlikely. All six photos were taken with an iPhone 6S - the size is almost always below 3MBs (just re-exported them and checked myself). Unclear what would make a standard jpeg appear as an unsupported mime type.

@trwnh My username is the same as here. I was using the default uploader.

**Comment by trwnh** [comment] 2019-03-14 02:51
This might be a bug in the classic uploader, then? If so, it would be a moot point once the default uploader is changed. (FWIW, the fact that only the first preview is shown is known but not desired, and only applies to the classic uploader anyway.)

Could you verify whether you can consistently reproduce failure with the "experimental UI" uploader? And could you share direct uploads of the problematic images to some file host (Box, Drive, etc) so we can see if it can be reproduced with just the images?

**Comment by dansup** [comment] 2019-03-14 04:49
@ricardojmendez Are the photos HEIC/HEIF format? If so this is a duplicate of #749

**Comment by ricardojmendez** [comment] 2019-03-14 06:16
> @ricardojmendez Are the photos HEIC/HEIF format? If so this is a duplicate of #749

@dansup Vanilla iPhone jpeg straight from iPhotos, afaik, unless something automagic is happening without my knowledge.

**Comment by ricardojmendez** [comment] 2019-03-14 06:18
> Could you verify whether you can consistently reproduce failure with the "experimental UI" uploader? And could you share direct uploads of the problematic images to some file host (Box, Drive, etc) so we can see if it can be reproduced with just the images?

I'll need to find the right selection of six I was testing with, which unfortunately I don't have on hand (it was a random sample). Will report back.

**Comment by dansup** [comment] 2019-03-17 08:04
I cannot reproduce this bug without more info. Feel free to re-open if you can provide the photos and browser/device type!

**Closed as completed by dansup** 2019-03-17 08:04 UTC
