### ISSUE TITLE
[Feature] [UI] [Mobile] Android mobile icon

### ISSUE THREAD

**Issue by Nikoos** [pixelfed/pixelfed#393] opened 2018-08-19 16:38 UTC
Hello,

An icon should be displayed when a bookmark is created on a Android desktop.

Actually there is no pixelfed icon displayed.

Regards,

Nikos

**Comment by Nikoos** [comment] 2018-08-22 15:50
Hello @dansup 

I am actually away from my main computer. But back in some days, I will try to propose a modification through a pr (my first one).

Regards Nikoos (nikos on mastodon)

**Comment by dansup** [comment] 2018-09-15 17:11
Duplicate of #233

**Closed as completed by dansup** 2018-09-15 17:11 UTC
