### ISSUE TITLE
The gallery arrow is not visible on the white background

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1098] opened 2019-03-30 12:36 UTC
If the gallery contains portrait images, the arrow to switch between the images is not visible on the white background.

A landscape format image, everything is OK:

![Bildschirmfoto 2019-03-30 um 13 25 46](https://user-images.githubusercontent.com/10457918/55276129-310bdb00-52f0-11e9-93a1-df27abdfe01e.png)

A upright image, the arrow is gone:

![Bildschirmfoto 2019-03-30 um 13 30 52](https://user-images.githubusercontent.com/10457918/55276142-5e588900-52f0-11e9-9c7d-6f22dc92fd9a.png)

Tested on [https://pixelfed.de](https://pixelfed.de) today.

**Comment by trwnh** [comment] 2019-03-30 16:33
Duplicate of #796

**Closed as completed by trwnh** 2019-03-30 16:33 UTC
