### ISSUE TITLE
Image rotation not working in preview mode

### ISSUE THREAD

**Issue by jranma** [pixelfed/pixelfed#1460] opened 2019-06-24 11:29 UTC
Image rotation is not working in preview mode (landscape instead of portrait). 
When the picture is posted, it's correct. Dispite this, the preview is very confusing. 
Preview mode doesn't take into account EXIF rotation data.

**Comment by okpierre** [comment] 2019-06-24 17:50
Possible duplicate of https://github.com/pixelfed/pixelfed/issues/1068?

**Comment by dansup** [comment] 2019-06-24 19:12
Duplicate of #1068

**Closed as completed by dansup** 2019-06-24 19:12 UTC
