### ISSUE TITLE
Permit login with username.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [pixelfed/pixelfed#4852] opened 2024-01-06 14:17 UTC
Although the account number is preferable when authenticating in a consistent manner, the username is more forward-facing, and demonstrates better which account is being authenticated in a credential manager than the account number does, yet isn't variable like the e-mail address field is.

**Comment by dansup** [comment] 2024-01-06 18:29
Duplicate of #494

**Closed as not planned by dansup** 2024-01-06 18:29 UTC

**Comment by roke-julian-lockhart** [comment] 2024-01-06 19:24
> https://github.com/pixelfed/pixelfed/issues/4852#event-11409199295

This isn't completed. It should be closed as unplanned.
