### ISSUE TITLE
Can't see posts from external instances, global feed is empty

### ISSUE THREAD

**Issue by piratenpanda** [pixelfed/pixelfed#3427] opened 2022-05-08 12:53 UTC
Just to rule out user mistake I'm opening an issue. I can find external users when searching via @username@instance and I can follow users also I can follow my pixelfed user from my mastodon account. Yet I don't see pictures on remote instances and my global feed is empty. Access log for the global feed shows:

```
 [08/May/2022:12:42:44 +0000] "GET /api/pixelfed/v1/timelines/network?max_id=0&limit=6 HTTP/2.0" 200 1847 "https://pixelfed.pandainthecloud.de/i/web/timeline/global" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
```

I also see something like
```
[08/May/2022:00:01:36 +0000] "POST /f/inbox HTTP/1.1" 200 5158 "-" "http.rb/5.0.4 (Mastodon/3.5.2; +https://mastodon.social/)"
[08/May/2022:00:02:53 +0000] "GET /.well-known/nodeinfo HTTP/1.1" 200 5827 "-" "Friendica 'Siberian Iris' 2022.03-1452; https://social.cyano.at"
[08/May/2022:00:02:53 +0000] "GET /api/nodeinfo/2.0.json HTTP/1.1" 200 977 "-" "Friendica 'Siberian Iris' 2022.03-1452; https://social.cyano.at"
[08/May/2022:00:02:53 +0000] "GET /poco HTTP/1.1" 404 6029 "-" "Friendica 'Siberian Iris' 2022.03-1452; https://social.cyano.at"
[08/May/2022:00:02:53 +0000] "GET /api/v1/directory?limit=1 HTTP/1.1" 404 5070 "-" "Friendica 'Siberian Iris' 2022.03-1452; https://social.cyano.at"
 [08/May/2022:00:02:53 +0000] "GET /api/v1/instance/activity HTTP/1.1" 404 5086 "-" "Friendica 'Siberian Iris' 2022.03-1452; https://social.cyano.at"
```
Horizon is running fine, at least it shows "active" in the dashboard. Don't know if this all that needs to run. 

Diagnostic output from the admin panel:
=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
APP_URL: https://pixelfed.pandainthecloud.de
APP_DOMAIN: pixelfed.pandainthecloud.de
Version: 0.11.2-7a0acebf
PHP: 8.0.14
Database: mysql (8.0.28)
Bootstrap: Writable
Storage: Writable
Image Driver: gd
REDIS Ping: ✅
PHP memory_limit: 1024M
PHP post_max_size: 256M
PHP upload_max_filesize: 256M
APP Cache Driver: redis
APP Mail Driver: log
APP Mail Host: smtp.***********
APP Queue Driver: redis
APP Session Driver: redis
APP Session Lifetime: 86400
APP Session Domain: pixelfed.pandainthecloud.de
CONFIG pixelfed:
{"domain":{"admin":"pixelfed.pandainthecloud.de","app":"pixelfed.pandainthecloud.de"},"version":"0.11.2","nodeinfo":{"url":"https://pixelfed.pandainthecloud.de/api/nodeinfo/2.0.json"},"memory_limit":"1024M","open_registration":false,"max_account_size":1000000,"max_photo_size":"15000","max_avatar_size":2000,"max_caption_length":"150","max_bio_length":125,"max_name_length":30,"min_password_length":8,"max_album_length":"4","enforce_email_verification":false,"image_quality":80,"account_deletion":true,"account_delete_after":false,"cloud_storage":false,"max_users":"10","optimize_image":true,"optimize_video":true,"user_invites":{"enabled":false,"limit":{"total":0,"daily":0,"monthly":0}},"max_collection_length":18,"media_types":"image/jpeg,image/png,image/gif","enforce_account_limit":true,"import":{"instagram":{"enabled":false,"limits":{"posts":100,"size":5000}}},"oauth_enabled":false,"bouncer":{"enabled":false},"media_fast_process":true,"max_altext_length":1000}
CONFIG federation:
{"activitypub":{"enabled":true,"outbox":true,"inbox":true,"sharedInbox":true,"remoteFollow":true,"delivery":{"timeout":30,"concurrency":10,"logger":{"enabled":false,"driver":"log"}}},"atom":{"enabled":true},"avatars":{"store_local":true},"nodeinfo":{"enabled":true},"webfinger":{"enabled":true},"network_timeline":true,"custom_emoji":{"enabled":false,"max_size":2000000}}
ACTIVITYPUB instance actor created: ✅
ACTIVITYPUB instance actor cached: ✅
OAUTH enabled: ✅
OAUTH token_expiration 365 days
OAUTH public key exists: ✅
OAUTH private key exists: ✅
========= END =========

edit: Pixeldroid now works

**Comment by dansup** [comment] 2022-05-09 04:42
You will only see new posts from remote accounts in your feeds, unless you search via url older posts. Can you confirm if your global feed is still empty?

**Comment by piratenpanda** [comment] 2022-05-09 05:39
How would I do that?

**Comment by piratenpanda** [comment] 2022-05-09 08:50
Ok so I copied a link to a picture in my search field. Now I see that specific image when I search for the user account and this is the only picture in my global feed. Is there an easier way to find whole instances and all posts there?

**Comment by dansup** [comment] 2022-05-09 09:37
> Ok so I copied a link to a picture in my search field. Now I see that specific image when I search for the user account and this is the only picture in my global feed. Is there an easier way to find whole instances and all posts there?

No, you can't search a whole instance or remote profile and expect to import all posts. The fediverse does not work that way, you'll see new posts from remote accounts you follow in your feeds.

Closing this as it's not a bug.

**Closed as completed by dansup** 2022-05-09 09:37 UTC

**Comment by piratenpanda** [comment] 2022-05-09 09:39
I see. So there is also no way to see older posts of people after I follow them?

**Comment by piratenpanda** [comment] 2022-05-09 09:43
Exploring hashtags like on diaspora* would make discovering other people really nice and easy. I don't know if this is possible though
