### ISSUE TITLE
Unable to change from "Hidden from public feeds" to public

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3772] opened 2022-11-14 22:43 UTC
My images are shown as "Hidden from public feeds" with no clear way to change it. So essentially I am sharing images with just me (very new to pixelfed so may be missing something)

![image](https://user-images.githubusercontent.com/2314200/201783224-4a8a5a30-bcfc-407d-9847-fd22f46b8d87.png)

**Comment by seven1m** [comment] 2022-11-23 19:06
Same for me. I have posted 4 times, every time being extra careful to select "Public" for the audience. Yet every post is the same as this... shown only to me or by visiting the URL directly.

**Comment by zcraber** [comment] 2022-11-30 13:02
Same here.

**Comment by seven1m** [comment] 2022-11-30 15:45
I ended up switching instances because of this. Pixelfed.social works as expected. 🤷‍♂️

**Comment by seven1m** [comment] 2022-11-30 16:39
@trwnh can you add a note about why you closed this? Is this a misconfiguration of certain pixelfed instances? If so, should we at least add a note about how to fix it for those instances?

**Comment by trwnh** [comment] 2022-11-30 16:50
Likely this is the result of your posts being forced to unlisted by the admin of your instance. In any case it is not an issue with Pixelfed

**Comment by seven1m** [comment] 2022-11-30 16:58
Every post on this particular instance goes unlisted for me. I have asked the instance admin and they don't know what causes it. Is there a particular configuration option that would cause this? (I appreciate your patience in educating me on this issue.)

**Comment by trwnh** [comment] 2022-11-30 17:01
Can you link to any affected posts?

**Comment by seven1m** [comment] 2022-11-30 17:02
Sure, here is one: https://pixelfed.sdf.org/p/seven1m/501214805990548624

All three posts on my profile are unlisted: https://pixelfed.sdf.org/seven1m

**Comment by ghost** [comment] 2022-12-02 17:24
Have a look at [https://github.com/pixelfed/pixelfed/issues/3872#issuecomment-1335562917](url) which seemed to be the same problem, got fixed after reviewing my posts which were somehow classified as "under review". Maybe this helps you, too!

**Comment by seven1m** [comment] 2022-12-02 18:24
Thank you @OliverPifferi! I have given up on the particular SDF instance for now, but it's nice to know the cause of this. If this is a widespread issue amongst instance admins, I wonder if some adjustments to the UI would help make it more obvious that users' posts are being hidden.

**Comment by trwnh** [comment] 2022-12-02 19:16
Closing in favor of #3872 then

**Closed as completed by trwnh** 2022-12-02 19:16 UTC
