### ISSUE TITLE
The "gallery counter" is not updated while slideshow

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1097] opened 2019-03-30 12:26 UTC
As you can see on the screenshots in issue #1096 the counter shows always the same numbers during the whole slideshow. It is only updated if you manually switch the images by clicking.

Tested on [https://pixelfed.de](https://pixelfed.de) today

**Comment by trwnh** [comment] 2019-03-30 16:33
Duplicate of #796

**Comment by dansup** [comment] 2019-04-03 00:19
@Vertux I have reproduced this bug, it will be fixed in the next batch of commits!

**Comment by dansup** [comment] 2019-12-09 02:23
We no longer use this album UI

**Closed as completed by dansup** 2019-12-09 02:23 UTC
Labels: 👀 UI
