### ISSUE TITLE
Unable to show profiles and conversations on other services

### ISSUE THREAD

**Issue by rickgardner077** [pixelfed/pixelfed#3415] opened 2022-05-03 08:02 UTC
I am unable to view profiles that are located on other services in the Fediverse (https://my.pixelfed/i/web/profile/xxx).

The page loads only the navbar header (including pixelfed logo, search bar and my profile picture with dropdown). The rest of the page is not rendered.

The access log shows that the page throws an Internal Server Error 500:
my.pixelfed:443 2a02:810b:: - - [03/May/2022:09:41:27 +0200] "GET /api/v1/accounts/relationships?id[]=xxx HTTP/2.0" 500 1260 "https://my.pixelfed/i/web/profile/xxx" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

Similar error thrown when trying to access conversations: 
"GET /api/v1/conversations?scope=inbox HTTP/2.0" 500

Error occurs independent of web browser used for viewing.

The instance was installed on [uberspace.de U7.12.1](https://manual.uberspace.de/) by following their [installation guide](https://lab.uberspace.de/guide_pixelfed/).

**Comment by qwertzdenek** [comment] 2022-05-18 13:34
I can confirm that. The profile I try to open is local but has some remote relationships.

version v0.11.3

**Comment by qwertzdenek** [comment] 2022-05-25 10:42
@rickgardner077 seems to be fixed in latest dev revision

**Closed as completed** 2022-06-11 11:23 UTC
