### ISSUE TITLE
Unable to login and get a 403 Error

### ISSUE THREAD

**Issue by 5uie** [pixelfed/pixelfed#3416] opened 2022-05-03 09:54 UTC
Hello, thank you for the beautiful experience of using pixelfed on the web. Apologies if this is the wrong place to post this as an issue. Please do let me know where to post, and I will move it accordingly.

Does anyone know why it isn’t possible to log into pixelfed.social using Mastodon clients? I’ve tried with the official iOS Mastodon client, Tootle and Metatext. I get a 403 error for it, while other pixelfed instances work fine. Please see attached screenshots below,
![Error403_metatext_ps](https://user-images.githubusercontent.com/104305869/166434265-37752359-b3d5-4d97-aad0-58776c4f1ece.png)
![Error403_Metatext](https://user-images.githubusercontent.com/104305869/166434271-369937d5-bc1c-47bd-a8d4-9b6828165e57.png)
![IMG_7723](https://user-images.githubusercontent.com/104305869/166434283-b910109d-726a-4a44-9ad5-46103fdd3c7c.jpg)
![IMG_7722](https://user-images.githubusercontent.com/104305869/166434292-18ae03d5-6420-40fd-b2da-222c57a774ee.JPG)
![IMG_7721](https://user-images.githubusercontent.com/104305869/166434303-5fbf3f95-b6bf-41ed-bb7a-6e1063cdf71f.JPG)

**Comment by 5uie** [comment] 2022-05-13 16:14
Hello, this error persists for me. Does anyone else see this error?

**Comment by dansup** [comment] 2022-05-14 06:48
@5uie I can't reproduce this, I can log in to pixelfed.social using MetaText perfectly fine. This might be Cloudflare WAF related, what country do you live in?

**Comment by 5uie** [comment] 2022-05-15 11:41
> @5uie I can't reproduce this, I can log in to pixelfed.social using MetaText perfectly fine. This might be Cloudflare WAF related, what country do you live in?

Thanks for the response @dansup, how can I share this location with you privately? I am not comfortable sharing this on GitHub.

Do all instances/servers use Cloudflare WAF or is it only pixelfed.social that uses it?

**Comment by dansup** [comment] 2022-06-11 11:24
Fixed in latest commits! Feel free to re-open this if you still have problems

**Closed as completed by dansup** 2022-06-11 11:24 UTC

**Comment by 5uie** [comment] 2022-06-20 07:31
@dansup Thank you for checking, but the 403 error persists across clients (metatext and ios official client) when logging into pixelfed.social. Also, I am unable to re-open the issue. Should I start a new one?
