### ISSUE TITLE
better UI for liking a post

### ISSUE THREAD

**Issue by Strubbl** [pixelfed/pixelfed#1804] opened 2019-11-01 12:51 UTC
Hi, 
i want to propose a feature, where the user can see, that he clicked the heart-button of a post. The current situation is confusing since i do not know if i missed to click the heart-button by a few pixels of if i successfully hit it.

Current situation:
* i click on the like button (heart frame)
* after 1 to 3 seconds the heart frame gets colored in red and i know the like is saved

better situation:
* i click on the like button (heart frame)
* the like button shows immediate reaction, that i clicked it, e.g. the heart frame filled with grey color
* after 1 to 3 seconds the heart frame gets colored in red and i know the like is saved

What do you think?

**Comment by trwnh** [comment] 2019-11-01 18:35
Duplicate of #1286

**Closed as completed by trwnh** 2019-11-01 18:35 UTC
