### ISSUE TITLE
Location no longer working 

### ISSUE THREAD

**Issue by orangemelo11** [pixelfed/pixelfed#4239] opened 2023-03-18 12:59 UTC
Cannot add a location while posting a photo using postgral database latest version of pf tried php artisan imprort:cities doesn’t work either

**Comment by x64x2** [comment] 2023-03-19 02:38
It's a feature not a bug

**Comment by orangemelo11** [comment] 2023-03-19 02:41
when i type it doesn’t drop down any location as before anymore it doesn’t work that’s what I meant

**Comment by dansup** [comment] 2023-03-29 08:20
@orangemelo11 @s0mt0chukwu fixed in [64a4a00](https://github.com/pixelfed/pixelfed/commit/64a4a0060aeafa5b204ab6e3151d5c146d0fd69f)

**Closed as completed by dansup** 2023-03-29 08:20 UTC
