### ISSUE TITLE
Allow edit of NSFW (CW) post

### ISSUE THREAD

**Issue by lapineige** [pixelfed/pixelfed#1557] opened 2019-07-28 11:27 UTC
Currently it's not possible to edit the NSFW status of a post.
In case of error, there is no way to change it, except by reuploading the content in a new post (and deleting the older one).
This is especially unhandy when one forgets to add the CW/NSFW status, and is reluctant to loose all likes/shares/comment to improve this.

(Related to #408 I suppose)

**Comment by trwnh** [comment] 2019-07-29 17:03
Duplicate of #823

**Closed as completed by trwnh** 2019-07-29 17:03 UTC
